// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AlertItem
 */
export type AlertItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * AlertsResponse
 */
export type AlertsResponse = {
    /**
     * Alerts
     */
    alerts: Array<AlertItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * AutoResearchRequest
 *
 * Request body for dispatching an autoresearch run.
 */
export type AutoResearchRequest = {
    /**
     * Markets
     */
    markets: Array<MarketSpecSchema>;
    /**
     * N Trials
     */
    n_trials?: number;
    /**
     * Min Wfe
     */
    min_wfe?: number;
    /**
     * Seed
     */
    seed?: number;
    /**
     * Strategy Mode
     *
     * Strategy variant: bidirectional (default), long_only, or regime_gated
     */
    strategy_mode?: string;
};

/**
 * BackfillRequest
 *
 * Request body for triggering a backfill.
 */
export type BackfillRequest = {
    /**
     * Market
     */
    market?: string | null;
    /**
     * Symbol
     */
    symbol?: string | null;
};

/**
 * BackfillStatusResponse
 *
 * Response body for backfill status.
 */
export type BackfillStatusResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Status
     */
    status: string;
    /**
     * Last Fetched Date
     */
    last_fetched_date: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
};

/**
 * BacktestResponse
 *
 * Response model for a backtest record.
 */
export type BacktestResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Strategy Id
     */
    strategy_id: string | null;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    } | null;
    /**
     * Walk Forward
     */
    walk_forward: {
        [key: string]: unknown;
    } | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * BacktestRunRequest
 *
 * Request body for dispatching a backtest run.
 */
export type BacktestRunRequest = {
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Initial Capital
     */
    initial_capital?: number;
};

/**
 * ExperimentResponse
 *
 * Response for a single experiment record.
 */
export type ExperimentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Study Name
     */
    study_name: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Composite Score
     */
    composite_score: number;
    /**
     * Wfe Score
     */
    wfe_score: number;
    /**
     * Status
     */
    status: string;
    /**
     * Config Json
     */
    config_json: {
        [key: string]: unknown;
    };
    /**
     * Metrics Json
     */
    metrics_json: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ExposureItem
 */
export type ExposureItem = {
    /**
     * Category
     */
    category: string;
    /**
     * Value
     */
    value: number;
};

/**
 * ExposureResponse
 */
export type ExposureResponse = {
    /**
     * Exposures
     */
    exposures: Array<ExposureItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * FetchRequest
 *
 * Request body for triggering a data fetch.
 */
export type FetchRequest = {
    /**
     * Market
     */
    market: string;
    /**
     * Symbol
     */
    symbol?: string | null;
    /**
     * Interval
     */
    interval?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HoldingResponse
 */
export type HoldingResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Weight
     */
    weight: number;
    /**
     * Shares
     */
    shares: number | null;
    /**
     * Entry Price
     */
    entry_price: number | null;
    /**
     * Entry Date
     */
    entry_date: string | null;
    /**
     * Stop Loss Pct
     */
    stop_loss_pct: number | null;
    /**
     * Current Price
     */
    current_price: number | null;
    /**
     * Unrealized Pnl
     */
    unrealized_pnl: number | null;
    /**
     * Side
     */
    side?: string;
};

/**
 * HoldingsResponse
 */
export type HoldingsResponse = {
    /**
     * Holdings
     */
    holdings: Array<HoldingResponse>;
    /**
     * Total Holdings
     */
    total_holdings: number;
};

/**
 * MarketSpecSchema
 *
 * A single market to search.
 */
export type MarketSpecSchema = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
};

/**
 * MessageResponse
 *
 * Generic message response.
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Task Id
     */
    task_id?: string | null;
};

/**
 * ModelVersionResponse
 *
 * Response model for a model version.
 */
export type ModelVersionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: number;
    /**
     * Status
     */
    status: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    } | null;
    /**
     * Feature List
     */
    feature_list: Array<unknown>;
    /**
     * Train Start
     */
    train_start: string | null;
    /**
     * Train End
     */
    train_end: string | null;
    /**
     * Artifact Path
     */
    artifact_path: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Message
     */
    error_message: string | null;
};

/**
 * NavPointResponse
 */
export type NavPointResponse = {
    /**
     * Date
     */
    date: string;
    /**
     * Total Nav
     */
    total_nav: number;
    /**
     * Holdings Value
     */
    holdings_value: number;
    /**
     * Cash
     */
    cash: number;
    /**
     * Holdings Count
     */
    holdings_count: number;
};

/**
 * OptimizeRequest
 *
 * Request body for dispatching a parameter optimization.
 */
export type OptimizeRequest = {
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Param Grid
     */
    param_grid: {
        [key: string]: unknown;
    };
    /**
     * Method
     */
    method?: string;
    /**
     * N Trials
     */
    n_trials?: number;
    /**
     * Target Metric
     */
    target_metric?: string;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * OrderResponse
 */
export type OrderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Action
     */
    action: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Status
     */
    status: string;
    /**
     * Price
     */
    price: number | null;
    /**
     * Broker Mode
     */
    broker_mode: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Side
     */
    side?: string;
};

/**
 * OrdersResponse
 */
export type OrdersResponse = {
    /**
     * Orders
     */
    orders: Array<OrderResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * PerformanceSummaryResponse
 */
export type PerformanceSummaryResponse = {
    /**
     * Nav Curve
     */
    nav_curve: Array<NavPointResponse>;
    /**
     * Total Return Pct
     */
    total_return_pct: number;
    /**
     * Max Drawdown Pct
     */
    max_drawdown_pct: number;
    /**
     * Sharpe Ratio
     */
    sharpe_ratio: number | null;
    /**
     * Total Trades
     */
    total_trades: number;
    /**
     * Total Realized Pnl
     */
    total_realized_pnl: number;
};

/**
 * PerpHoldingResponse
 */
export type PerpHoldingResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Side
     */
    side: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Entry Price
     */
    entry_price: number;
    /**
     * Leverage
     */
    leverage: number;
    /**
     * Liquidation Price
     */
    liquidation_price: number;
    /**
     * Margin Ratio
     */
    margin_ratio: number;
    /**
     * Unrealized Pnl
     */
    unrealized_pnl: number;
    /**
     * Cumulative Funding Cost
     */
    cumulative_funding_cost: number;
    /**
     * Current Price
     */
    current_price?: number | null;
};

/**
 * PerpHoldingsResponse
 */
export type PerpHoldingsResponse = {
    /**
     * Holdings
     */
    holdings: Array<PerpHoldingResponse>;
    /**
     * Total Holdings
     */
    total_holdings: number;
};

/**
 * PredictRequest
 *
 * Request body for model prediction.
 */
export type PredictRequest = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Use Latest Data
     */
    use_latest_data?: boolean;
};

/**
 * QualityScoreResponse
 */
export type QualityScoreResponse = {
    /**
     * Time
     */
    time: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Score
     */
    score: number;
    /**
     * Completeness
     */
    completeness: number;
    /**
     * Consistency
     */
    consistency: number;
    /**
     * Anomaly Free
     */
    anomaly_free: number;
    /**
     * Timeliness
     */
    timeliness: number;
};

/**
 * QualityScoresResponse
 */
export type QualityScoresResponse = {
    /**
     * Scores
     */
    scores: Array<QualityScoreResponse>;
};

/**
 * RiskRuleCreate
 *
 * Request body for creating a new risk rule.
 */
export type RiskRuleCreate = {
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Priority
     */
    priority?: number;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * RiskRuleResponse
 *
 * Response model for a risk rule.
 */
export type RiskRuleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Priority
     */
    priority: number;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RiskRuleUpdate
 *
 * Request body for updating an existing risk rule.
 *
 * Only provided (non-None) fields are applied.
 */
export type RiskRuleUpdate = {
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
};

/**
 * SentimentCreate
 *
 * Request body for creating a sentiment score.
 */
export type SentimentCreate = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Score
     */
    score: number;
};

/**
 * SentimentResponse
 *
 * Response body for a sentiment score.
 */
export type SentimentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Score
     */
    score: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SignalResponse
 *
 * Response model for a signal record.
 */
export type SignalResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Strategy Id
     */
    strategy_id: string | null;
    /**
     * Model Id
     */
    model_id: string | null;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Instrument
     */
    instrument: string;
    /**
     * Action
     */
    action: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Quantity Pct
     */
    quantity_pct: number | null;
    /**
     * Signal Time
     */
    signal_time: string;
    /**
     * Valid Until
     */
    valid_until: string | null;
    /**
     * Interval
     */
    interval: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * StrategyCreate
 *
 * Request body for creating a new strategy.
 */
export type StrategyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Model Version Id
     */
    model_version_id?: string | null;
};

/**
 * StrategyResponse
 *
 * Response model for a strategy.
 */
export type StrategyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Model Version Id
     */
    model_version_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * StrategyUpdate
 *
 * Request body for updating an existing strategy.
 *
 * Only provided (non-None) fields are applied.
 */
export type StrategyUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Symbol
     */
    symbol?: string | null;
    /**
     * Market
     */
    market?: string | null;
    /**
     * Interval
     */
    interval?: string | null;
    /**
     * Model Version Id
     */
    model_version_id?: string | null;
};

/**
 * StressTestRequest
 */
export type StressTestRequest = {
    /**
     * Scenario Name
     */
    scenario_name: string;
    /**
     * Custom Shocks
     */
    custom_shocks?: {
        [key: string]: number;
    } | null;
};

/**
 * StressTestStatusResponse
 */
export type StressTestStatusResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * StressTestTriggerResponse
 */
export type StressTestTriggerResponse = {
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * TaskStatusResponse
 *
 * Response for task status polling.
 */
export type TaskStatusResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress?: {
        [key: string]: unknown;
    } | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * TrainRequest
 *
 * Request body for dispatching a model training job.
 */
export type TrainRequest = {
    /**
     * Model Name
     */
    model_name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
    /**
     * Feature List
     */
    feature_list?: Array<string>;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Label Mode
     */
    label_mode?: string;
};

/**
 * TransitionRequest
 *
 * Optional body for lifecycle transitions (e.g. attach metrics).
 */
export type TransitionRequest = {
    /**
     * Metrics
     */
    metrics?: {
        [key: string]: unknown;
    } | null;
};

/**
 * VaRResponse
 */
export type VaRResponse = {
    /**
     * Snapshots
     */
    snapshots: Array<VaRSnapshotResponse>;
};

/**
 * VaRSnapshotResponse
 */
export type VaRSnapshotResponse = {
    /**
     * Method
     */
    method: string;
    /**
     * Var 95
     */
    var_95: number;
    /**
     * Var 99
     */
    var_99: number;
    /**
     * Cvar 95
     */
    cvar_95: number;
    /**
     * Cvar 99
     */
    cvar_99: number;
    /**
     * Portfolio Value
     */
    portfolio_value: number;
    /**
     * Holding Period
     */
    holding_period: number;
    /**
     * As Of
     */
    as_of?: string | null;
    /**
     * Computed At
     */
    computed_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VirtualPositionResponse
 *
 * Response model for a virtual portfolio position.
 */
export type VirtualPositionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Instrument
     */
    instrument: string;
    /**
     * Side
     */
    side: string;
    /**
     * Quantity Pct
     */
    quantity_pct: number;
    /**
     * Entry Time
     */
    entry_time: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerFetchDataFetchPostData = {
    body: FetchRequest;
    path?: never;
    query?: never;
    url: '/data/fetch';
};

export type TriggerFetchDataFetchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerFetchDataFetchPostError = TriggerFetchDataFetchPostErrors[keyof TriggerFetchDataFetchPostErrors];

export type TriggerFetchDataFetchPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type TriggerFetchDataFetchPostResponse = TriggerFetchDataFetchPostResponses[keyof TriggerFetchDataFetchPostResponses];

export type TriggerBackfillEndpointDataBackfillPostData = {
    body: BackfillRequest;
    path?: never;
    query?: never;
    url: '/data/backfill';
};

export type TriggerBackfillEndpointDataBackfillPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerBackfillEndpointDataBackfillPostError = TriggerBackfillEndpointDataBackfillPostErrors[keyof TriggerBackfillEndpointDataBackfillPostErrors];

export type TriggerBackfillEndpointDataBackfillPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type TriggerBackfillEndpointDataBackfillPostResponse = TriggerBackfillEndpointDataBackfillPostResponses[keyof TriggerBackfillEndpointDataBackfillPostResponses];

export type GetBackfillStatusDataBackfillStatusGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
    };
    url: '/data/backfill/status';
};

export type GetBackfillStatusDataBackfillStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBackfillStatusDataBackfillStatusGetError = GetBackfillStatusDataBackfillStatusGetErrors[keyof GetBackfillStatusDataBackfillStatusGetErrors];

export type GetBackfillStatusDataBackfillStatusGetResponses = {
    /**
     * Response Get Backfill Status Data Backfill Status Get
     *
     * Successful Response
     */
    200: Array<BackfillStatusResponse>;
};

export type GetBackfillStatusDataBackfillStatusGetResponse = GetBackfillStatusDataBackfillStatusGetResponses[keyof GetBackfillStatusDataBackfillStatusGetResponses];

export type ListSentimentSentimentGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Symbol
         *
         * Symbol to query sentiment for
         */
        symbol: string;
        /**
         * Market
         *
         * Optional market filter
         */
        market?: string | null;
        /**
         * Limit
         *
         * Max results to return
         */
        limit?: number;
    };
    url: '/sentiment';
};

export type ListSentimentSentimentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSentimentSentimentGetError = ListSentimentSentimentGetErrors[keyof ListSentimentSentimentGetErrors];

export type ListSentimentSentimentGetResponses = {
    /**
     * Response List Sentiment Sentiment Get
     *
     * Successful Response
     */
    200: Array<SentimentResponse>;
};

export type ListSentimentSentimentGetResponse = ListSentimentSentimentGetResponses[keyof ListSentimentSentimentGetResponses];

export type CreateSentimentSentimentPostData = {
    body: SentimentCreate;
    path?: never;
    query?: never;
    url: '/sentiment';
};

export type CreateSentimentSentimentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSentimentSentimentPostError = CreateSentimentSentimentPostErrors[keyof CreateSentimentSentimentPostErrors];

export type CreateSentimentSentimentPostResponses = {
    /**
     * Successful Response
     */
    201: SentimentResponse;
};

export type CreateSentimentSentimentPostResponse = CreateSentimentSentimentPostResponses[keyof CreateSentimentSentimentPostResponses];

export type ListRuleTypesApiRiskRulesTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk-rules/types';
};

export type ListRuleTypesApiRiskRulesTypesGetResponses = {
    /**
     * Response List Rule Types Api Risk Rules Types Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListRuleTypesApiRiskRulesTypesGetResponse = ListRuleTypesApiRiskRulesTypesGetResponses[keyof ListRuleTypesApiRiskRulesTypesGetResponses];

export type ListRulesApiRiskRulesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk-rules';
};

export type ListRulesApiRiskRulesGetResponses = {
    /**
     * Response List Rules Api Risk Rules Get
     *
     * Successful Response
     */
    200: Array<RiskRuleResponse>;
};

export type ListRulesApiRiskRulesGetResponse = ListRulesApiRiskRulesGetResponses[keyof ListRulesApiRiskRulesGetResponses];

export type CreateRuleApiRiskRulesPostData = {
    body: RiskRuleCreate;
    path?: never;
    query?: never;
    url: '/api/risk-rules';
};

export type CreateRuleApiRiskRulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRuleApiRiskRulesPostError = CreateRuleApiRiskRulesPostErrors[keyof CreateRuleApiRiskRulesPostErrors];

export type CreateRuleApiRiskRulesPostResponses = {
    /**
     * Successful Response
     */
    201: RiskRuleResponse;
};

export type CreateRuleApiRiskRulesPostResponse = CreateRuleApiRiskRulesPostResponses[keyof CreateRuleApiRiskRulesPostResponses];

export type GetPortfolioApiRiskRulesPortfolioGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
    };
    url: '/api/risk-rules/portfolio';
};

export type GetPortfolioApiRiskRulesPortfolioGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPortfolioApiRiskRulesPortfolioGetError = GetPortfolioApiRiskRulesPortfolioGetErrors[keyof GetPortfolioApiRiskRulesPortfolioGetErrors];

export type GetPortfolioApiRiskRulesPortfolioGetResponses = {
    /**
     * Response Get Portfolio Api Risk Rules Portfolio Get
     *
     * Successful Response
     */
    200: Array<VirtualPositionResponse>;
};

export type GetPortfolioApiRiskRulesPortfolioGetResponse = GetPortfolioApiRiskRulesPortfolioGetResponses[keyof GetPortfolioApiRiskRulesPortfolioGetResponses];

export type DeleteRuleApiRiskRulesRuleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type DeleteRuleApiRiskRulesRuleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRuleApiRiskRulesRuleIdDeleteError = DeleteRuleApiRiskRulesRuleIdDeleteErrors[keyof DeleteRuleApiRiskRulesRuleIdDeleteErrors];

export type DeleteRuleApiRiskRulesRuleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRuleApiRiskRulesRuleIdDeleteResponse = DeleteRuleApiRiskRulesRuleIdDeleteResponses[keyof DeleteRuleApiRiskRulesRuleIdDeleteResponses];

export type GetRuleApiRiskRulesRuleIdGetData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type GetRuleApiRiskRulesRuleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleApiRiskRulesRuleIdGetError = GetRuleApiRiskRulesRuleIdGetErrors[keyof GetRuleApiRiskRulesRuleIdGetErrors];

export type GetRuleApiRiskRulesRuleIdGetResponses = {
    /**
     * Successful Response
     */
    200: RiskRuleResponse;
};

export type GetRuleApiRiskRulesRuleIdGetResponse = GetRuleApiRiskRulesRuleIdGetResponses[keyof GetRuleApiRiskRulesRuleIdGetResponses];

export type UpdateRuleApiRiskRulesRuleIdPatchData = {
    body: RiskRuleUpdate;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type UpdateRuleApiRiskRulesRuleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRuleApiRiskRulesRuleIdPatchError = UpdateRuleApiRiskRulesRuleIdPatchErrors[keyof UpdateRuleApiRiskRulesRuleIdPatchErrors];

export type UpdateRuleApiRiskRulesRuleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RiskRuleResponse;
};

export type UpdateRuleApiRiskRulesRuleIdPatchResponse = UpdateRuleApiRiskRulesRuleIdPatchResponses[keyof UpdateRuleApiRiskRulesRuleIdPatchResponses];

export type ListStrategiesStrategiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/strategies';
};

export type ListStrategiesStrategiesGetResponses = {
    /**
     * Response List Strategies Strategies Get
     *
     * Successful Response
     */
    200: Array<StrategyResponse>;
};

export type ListStrategiesStrategiesGetResponse = ListStrategiesStrategiesGetResponses[keyof ListStrategiesStrategiesGetResponses];

export type CreateStrategyStrategiesPostData = {
    body: StrategyCreate;
    path?: never;
    query?: never;
    url: '/strategies';
};

export type CreateStrategyStrategiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStrategyStrategiesPostError = CreateStrategyStrategiesPostErrors[keyof CreateStrategyStrategiesPostErrors];

export type CreateStrategyStrategiesPostResponses = {
    /**
     * Successful Response
     */
    201: StrategyResponse;
};

export type CreateStrategyStrategiesPostResponse = CreateStrategyStrategiesPostResponses[keyof CreateStrategyStrategiesPostResponses];

export type DeleteStrategyStrategiesStrategyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/strategies/{strategy_id}';
};

export type DeleteStrategyStrategiesStrategyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStrategyStrategiesStrategyIdDeleteError = DeleteStrategyStrategiesStrategyIdDeleteErrors[keyof DeleteStrategyStrategiesStrategyIdDeleteErrors];

export type DeleteStrategyStrategiesStrategyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteStrategyStrategiesStrategyIdDeleteResponse = DeleteStrategyStrategiesStrategyIdDeleteResponses[keyof DeleteStrategyStrategiesStrategyIdDeleteResponses];

export type GetStrategyStrategiesStrategyIdGetData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/strategies/{strategy_id}';
};

export type GetStrategyStrategiesStrategyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStrategyStrategiesStrategyIdGetError = GetStrategyStrategiesStrategyIdGetErrors[keyof GetStrategyStrategiesStrategyIdGetErrors];

export type GetStrategyStrategiesStrategyIdGetResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type GetStrategyStrategiesStrategyIdGetResponse = GetStrategyStrategiesStrategyIdGetResponses[keyof GetStrategyStrategiesStrategyIdGetResponses];

export type UpdateStrategyStrategiesStrategyIdPutData = {
    body: StrategyUpdate;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/strategies/{strategy_id}';
};

export type UpdateStrategyStrategiesStrategyIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStrategyStrategiesStrategyIdPutError = UpdateStrategyStrategiesStrategyIdPutErrors[keyof UpdateStrategyStrategiesStrategyIdPutErrors];

export type UpdateStrategyStrategiesStrategyIdPutResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type UpdateStrategyStrategiesStrategyIdPutResponse = UpdateStrategyStrategiesStrategyIdPutResponses[keyof UpdateStrategyStrategiesStrategyIdPutResponses];

export type ActivateStrategyStrategiesStrategyIdActivatePostData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/strategies/{strategy_id}/activate';
};

export type ActivateStrategyStrategiesStrategyIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateStrategyStrategiesStrategyIdActivatePostError = ActivateStrategyStrategiesStrategyIdActivatePostErrors[keyof ActivateStrategyStrategiesStrategyIdActivatePostErrors];

export type ActivateStrategyStrategiesStrategyIdActivatePostResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type ActivateStrategyStrategiesStrategyIdActivatePostResponse = ActivateStrategyStrategiesStrategyIdActivatePostResponses[keyof ActivateStrategyStrategiesStrategyIdActivatePostResponses];

export type DeactivateStrategyStrategiesStrategyIdDeactivatePostData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/strategies/{strategy_id}/deactivate';
};

export type DeactivateStrategyStrategiesStrategyIdDeactivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateStrategyStrategiesStrategyIdDeactivatePostError = DeactivateStrategyStrategiesStrategyIdDeactivatePostErrors[keyof DeactivateStrategyStrategiesStrategyIdDeactivatePostErrors];

export type DeactivateStrategyStrategiesStrategyIdDeactivatePostResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type DeactivateStrategyStrategiesStrategyIdDeactivatePostResponse = DeactivateStrategyStrategiesStrategyIdDeactivatePostResponses[keyof DeactivateStrategyStrategiesStrategyIdDeactivatePostResponses];

export type StartTrainingModelsTrainPostData = {
    body: TrainRequest;
    path?: never;
    query?: never;
    url: '/models/train';
};

export type StartTrainingModelsTrainPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartTrainingModelsTrainPostError = StartTrainingModelsTrainPostErrors[keyof StartTrainingModelsTrainPostErrors];

export type StartTrainingModelsTrainPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type StartTrainingModelsTrainPostResponse = StartTrainingModelsTrainPostResponses[keyof StartTrainingModelsTrainPostResponses];

export type ListModelsModelsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/models';
};

export type ListModelsModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsModelsGetError = ListModelsModelsGetErrors[keyof ListModelsModelsGetErrors];

export type ListModelsModelsGetResponses = {
    /**
     * Response List Models Models Get
     *
     * Successful Response
     */
    200: Array<ModelVersionResponse>;
};

export type ListModelsModelsGetResponse = ListModelsModelsGetResponses[keyof ListModelsModelsGetResponses];

export type GetModelVersionModelsVersionIdGetData = {
    body?: never;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/models/{version_id}';
};

export type GetModelVersionModelsVersionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelVersionModelsVersionIdGetError = GetModelVersionModelsVersionIdGetErrors[keyof GetModelVersionModelsVersionIdGetErrors];

export type GetModelVersionModelsVersionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type GetModelVersionModelsVersionIdGetResponse = GetModelVersionModelsVersionIdGetResponses[keyof GetModelVersionModelsVersionIdGetResponses];

export type ShadowModelModelsVersionIdShadowPostData = {
    /**
     * Body
     */
    body?: TransitionRequest | null;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/models/{version_id}/shadow';
};

export type ShadowModelModelsVersionIdShadowPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShadowModelModelsVersionIdShadowPostError = ShadowModelModelsVersionIdShadowPostErrors[keyof ShadowModelModelsVersionIdShadowPostErrors];

export type ShadowModelModelsVersionIdShadowPostResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type ShadowModelModelsVersionIdShadowPostResponse = ShadowModelModelsVersionIdShadowPostResponses[keyof ShadowModelModelsVersionIdShadowPostResponses];

export type ActivateModelModelsVersionIdActivatePostData = {
    /**
     * Body
     */
    body?: TransitionRequest | null;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/models/{version_id}/activate';
};

export type ActivateModelModelsVersionIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateModelModelsVersionIdActivatePostError = ActivateModelModelsVersionIdActivatePostErrors[keyof ActivateModelModelsVersionIdActivatePostErrors];

export type ActivateModelModelsVersionIdActivatePostResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type ActivateModelModelsVersionIdActivatePostResponse = ActivateModelModelsVersionIdActivatePostResponses[keyof ActivateModelModelsVersionIdActivatePostResponses];

export type PredictModelsVersionIdPredictPostData = {
    body: PredictRequest;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/models/{version_id}/predict';
};

export type PredictModelsVersionIdPredictPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PredictModelsVersionIdPredictPostError = PredictModelsVersionIdPredictPostErrors[keyof PredictModelsVersionIdPredictPostErrors];

export type PredictModelsVersionIdPredictPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type PredictModelsVersionIdPredictPostResponse = PredictModelsVersionIdPredictPostResponses[keyof PredictModelsVersionIdPredictPostResponses];

export type RunBacktestBacktestRunPostData = {
    body: BacktestRunRequest;
    path?: never;
    query?: never;
    url: '/backtest/run';
};

export type RunBacktestBacktestRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunBacktestBacktestRunPostError = RunBacktestBacktestRunPostErrors[keyof RunBacktestBacktestRunPostErrors];

export type RunBacktestBacktestRunPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunBacktestBacktestRunPostResponse = RunBacktestBacktestRunPostResponses[keyof RunBacktestBacktestRunPostResponses];

export type RunOptimizationBacktestOptimizePostData = {
    body: OptimizeRequest;
    path?: never;
    query?: never;
    url: '/backtest/optimize';
};

export type RunOptimizationBacktestOptimizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunOptimizationBacktestOptimizePostError = RunOptimizationBacktestOptimizePostErrors[keyof RunOptimizationBacktestOptimizePostErrors];

export type RunOptimizationBacktestOptimizePostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunOptimizationBacktestOptimizePostResponse = RunOptimizationBacktestOptimizePostResponses[keyof RunOptimizationBacktestOptimizePostResponses];

export type ListBacktestsBacktestGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Strategy Id
         */
        strategy_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/backtest';
};

export type ListBacktestsBacktestGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBacktestsBacktestGetError = ListBacktestsBacktestGetErrors[keyof ListBacktestsBacktestGetErrors];

export type ListBacktestsBacktestGetResponses = {
    /**
     * Response List Backtests Backtest Get
     *
     * Successful Response
     */
    200: Array<BacktestResponse>;
};

export type ListBacktestsBacktestGetResponse = ListBacktestsBacktestGetResponses[keyof ListBacktestsBacktestGetResponses];

export type GetBacktestBacktestBacktestIdGetData = {
    body?: never;
    path: {
        /**
         * Backtest Id
         */
        backtest_id: string;
    };
    query?: never;
    url: '/backtest/{backtest_id}';
};

export type GetBacktestBacktestBacktestIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBacktestBacktestBacktestIdGetError = GetBacktestBacktestBacktestIdGetErrors[keyof GetBacktestBacktestBacktestIdGetErrors];

export type GetBacktestBacktestBacktestIdGetResponses = {
    /**
     * Successful Response
     */
    200: BacktestResponse;
};

export type GetBacktestBacktestBacktestIdGetResponse = GetBacktestBacktestBacktestIdGetResponses[keyof GetBacktestBacktestBacktestIdGetResponses];

export type ListSignalsSignalsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
        /**
         * Symbol
         */
        symbol?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/signals';
};

export type ListSignalsSignalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSignalsSignalsGetError = ListSignalsSignalsGetErrors[keyof ListSignalsSignalsGetErrors];

export type ListSignalsSignalsGetResponses = {
    /**
     * Response List Signals Signals Get
     *
     * Successful Response
     */
    200: Array<SignalResponse>;
};

export type ListSignalsSignalsGetResponse = ListSignalsSignalsGetResponses[keyof ListSignalsSignalsGetResponses];

export type GetSignalSignalsSignalIdGetData = {
    body?: never;
    path: {
        /**
         * Signal Id
         */
        signal_id: string;
    };
    query?: never;
    url: '/signals/{signal_id}';
};

export type GetSignalSignalsSignalIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSignalSignalsSignalIdGetError = GetSignalSignalsSignalIdGetErrors[keyof GetSignalSignalsSignalIdGetErrors];

export type GetSignalSignalsSignalIdGetResponses = {
    /**
     * Successful Response
     */
    200: SignalResponse;
};

export type GetSignalSignalsSignalIdGetResponse = GetSignalSignalsSignalIdGetResponses[keyof GetSignalSignalsSignalIdGetResponses];

export type RunAutoresearchAutoresearchRunPostData = {
    body: AutoResearchRequest;
    path?: never;
    query?: never;
    url: '/autoresearch/run';
};

export type RunAutoresearchAutoresearchRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunAutoresearchAutoresearchRunPostError = RunAutoresearchAutoresearchRunPostErrors[keyof RunAutoresearchAutoresearchRunPostErrors];

export type RunAutoresearchAutoresearchRunPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunAutoresearchAutoresearchRunPostResponse = RunAutoresearchAutoresearchRunPostResponses[keyof RunAutoresearchAutoresearchRunPostResponses];

export type GetTaskStatusAutoresearchStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/autoresearch/status/{task_id}';
};

export type GetTaskStatusAutoresearchStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskStatusAutoresearchStatusTaskIdGetError = GetTaskStatusAutoresearchStatusTaskIdGetErrors[keyof GetTaskStatusAutoresearchStatusTaskIdGetErrors];

export type GetTaskStatusAutoresearchStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskStatusResponse;
};

export type GetTaskStatusAutoresearchStatusTaskIdGetResponse = GetTaskStatusAutoresearchStatusTaskIdGetResponses[keyof GetTaskStatusAutoresearchStatusTaskIdGetResponses];

export type StopAutoresearchAutoresearchStopTaskIdPostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/autoresearch/stop/{task_id}';
};

export type StopAutoresearchAutoresearchStopTaskIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopAutoresearchAutoresearchStopTaskIdPostError = StopAutoresearchAutoresearchStopTaskIdPostErrors[keyof StopAutoresearchAutoresearchStopTaskIdPostErrors];

export type StopAutoresearchAutoresearchStopTaskIdPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type StopAutoresearchAutoresearchStopTaskIdPostResponse = StopAutoresearchAutoresearchStopTaskIdPostResponses[keyof StopAutoresearchAutoresearchStopTaskIdPostResponses];

export type ListExperimentsAutoresearchExperimentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Study Name
         */
        study_name?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/autoresearch/experiments';
};

export type ListExperimentsAutoresearchExperimentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExperimentsAutoresearchExperimentsGetError = ListExperimentsAutoresearchExperimentsGetErrors[keyof ListExperimentsAutoresearchExperimentsGetErrors];

export type ListExperimentsAutoresearchExperimentsGetResponses = {
    /**
     * Response List Experiments Autoresearch Experiments Get
     *
     * Successful Response
     */
    200: Array<ExperimentResponse>;
};

export type ListExperimentsAutoresearchExperimentsGetResponse = ListExperimentsAutoresearchExperimentsGetResponses[keyof ListExperimentsAutoresearchExperimentsGetResponses];

export type GetProviderHealthApiDataQualityProvidersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/data-quality/providers';
};

export type GetProviderHealthApiDataQualityProvidersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQualityScoresApiDataQualityScoresGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Symbol
         *
         * Filter by symbol
         */
        symbol?: string | null;
        /**
         * Interval
         *
         * Filter by interval
         */
        interval?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/data-quality/scores';
};

export type GetQualityScoresApiDataQualityScoresGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQualityScoresApiDataQualityScoresGetError = GetQualityScoresApiDataQualityScoresGetErrors[keyof GetQualityScoresApiDataQualityScoresGetErrors];

export type GetQualityScoresApiDataQualityScoresGetResponses = {
    /**
     * Successful Response
     */
    200: QualityScoresResponse;
};

export type GetQualityScoresApiDataQualityScoresGetResponse = GetQualityScoresApiDataQualityScoresGetResponses[keyof GetQualityScoresApiDataQualityScoresGetResponses];

export type GetVarApiRiskVarGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk/var';
};

export type GetVarApiRiskVarGetResponses = {
    /**
     * Successful Response
     */
    200: VaRResponse;
};

export type GetVarApiRiskVarGetResponse = GetVarApiRiskVarGetResponses[keyof GetVarApiRiskVarGetResponses];

export type GetExposureApiRiskExposureGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk/exposure';
};

export type GetExposureApiRiskExposureGetResponses = {
    /**
     * Successful Response
     */
    200: ExposureResponse;
};

export type GetExposureApiRiskExposureGetResponse = GetExposureApiRiskExposureGetResponses[keyof GetExposureApiRiskExposureGetResponses];

export type TriggerStressTestApiRiskStressTestRunPostData = {
    body: StressTestRequest;
    path?: never;
    query?: never;
    url: '/api/risk/stress-test/run';
};

export type TriggerStressTestApiRiskStressTestRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerStressTestApiRiskStressTestRunPostError = TriggerStressTestApiRiskStressTestRunPostErrors[keyof TriggerStressTestApiRiskStressTestRunPostErrors];

export type TriggerStressTestApiRiskStressTestRunPostResponses = {
    /**
     * Successful Response
     */
    200: StressTestTriggerResponse;
};

export type TriggerStressTestApiRiskStressTestRunPostResponse = TriggerStressTestApiRiskStressTestRunPostResponses[keyof TriggerStressTestApiRiskStressTestRunPostResponses];

export type GetStressTestResultApiRiskStressTestTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/risk/stress-test/{task_id}';
};

export type GetStressTestResultApiRiskStressTestTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStressTestResultApiRiskStressTestTaskIdGetError = GetStressTestResultApiRiskStressTestTaskIdGetErrors[keyof GetStressTestResultApiRiskStressTestTaskIdGetErrors];

export type GetStressTestResultApiRiskStressTestTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: StressTestStatusResponse;
};

export type GetStressTestResultApiRiskStressTestTaskIdGetResponse = GetStressTestResultApiRiskStressTestTaskIdGetResponses[keyof GetStressTestResultApiRiskStressTestTaskIdGetResponses];

export type GetAlertsApiRiskAlertsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/risk/alerts';
};

export type GetAlertsApiRiskAlertsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlertsApiRiskAlertsGetError = GetAlertsApiRiskAlertsGetErrors[keyof GetAlertsApiRiskAlertsGetErrors];

export type GetAlertsApiRiskAlertsGetResponses = {
    /**
     * Successful Response
     */
    200: AlertsResponse;
};

export type GetAlertsApiRiskAlertsGetResponse = GetAlertsApiRiskAlertsGetResponses[keyof GetAlertsApiRiskAlertsGetResponses];

export type GetPerformanceApiPortfolioPerformanceGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         *
         * Filter by market (e.g., 'crypto_perp')
         */
        market?: string | null;
    };
    url: '/api/portfolio/performance';
};

export type GetPerformanceApiPortfolioPerformanceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPerformanceApiPortfolioPerformanceGetError = GetPerformanceApiPortfolioPerformanceGetErrors[keyof GetPerformanceApiPortfolioPerformanceGetErrors];

export type GetPerformanceApiPortfolioPerformanceGetResponses = {
    /**
     * Successful Response
     */
    200: PerformanceSummaryResponse;
};

export type GetPerformanceApiPortfolioPerformanceGetResponse = GetPerformanceApiPortfolioPerformanceGetResponses[keyof GetPerformanceApiPortfolioPerformanceGetResponses];

export type GetHoldingsApiPortfolioHoldingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/holdings';
};

export type GetHoldingsApiPortfolioHoldingsGetResponses = {
    /**
     * Successful Response
     */
    200: HoldingsResponse;
};

export type GetHoldingsApiPortfolioHoldingsGetResponse = GetHoldingsApiPortfolioHoldingsGetResponses[keyof GetHoldingsApiPortfolioHoldingsGetResponses];

export type GetOrdersApiPortfolioOrdersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         *
         * Filter by order status
         */
        status?: string | null;
        /**
         * Limit
         *
         * Max orders to return
         */
        limit?: number;
    };
    url: '/api/portfolio/orders';
};

export type GetOrdersApiPortfolioOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersApiPortfolioOrdersGetError = GetOrdersApiPortfolioOrdersGetErrors[keyof GetOrdersApiPortfolioOrdersGetErrors];

export type GetOrdersApiPortfolioOrdersGetResponses = {
    /**
     * Successful Response
     */
    200: OrdersResponse;
};

export type GetOrdersApiPortfolioOrdersGetResponse = GetOrdersApiPortfolioOrdersGetResponses[keyof GetOrdersApiPortfolioOrdersGetResponses];

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/perp-holdings';
};

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses = {
    /**
     * Successful Response
     */
    200: PerpHoldingsResponse;
};

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetResponse = GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses[keyof GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses];
