// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AlertItem
 */
export type AlertItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * AlertsResponse
 */
export type AlertsResponse = {
    /**
     * Alerts
     */
    alerts: Array<AlertItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * AutoResearchRequest
 *
 * Request body for dispatching an autoresearch run.
 */
export type AutoResearchRequest = {
    /**
     * Markets
     */
    markets: Array<MarketSpecSchema>;
    /**
     * N Trials
     */
    n_trials?: number;
    /**
     * Min Wfe
     */
    min_wfe?: number;
    /**
     * Seed
     */
    seed?: number;
    /**
     * Strategy Mode
     *
     * Strategy variant: bidirectional (default), long_only, or regime_gated
     */
    strategy_mode?: string;
};

/**
 * BackfillRequest
 *
 * Request body for triggering a backfill.
 */
export type BackfillRequest = {
    /**
     * Market
     */
    market?: string | null;
    /**
     * Symbol
     */
    symbol?: string | null;
};

/**
 * BackfillStatusResponse
 *
 * Response body for backfill status.
 */
export type BackfillStatusResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Status
     */
    status: string;
    /**
     * Last Fetched Date
     */
    last_fetched_date: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
};

/**
 * BacktestEquityPointResponse
 *
 * Response model for a single equity curve data point.
 */
export type BacktestEquityPointResponse = {
    /**
     * Time
     */
    time: string;
    /**
     * Equity
     */
    equity: number;
    /**
     * Drawdown
     */
    drawdown: number;
};

/**
 * BacktestEquityResponse
 *
 * Response model wrapping the equity curve for a backtest.
 */
export type BacktestEquityResponse = {
    /**
     * Backtest Id
     */
    backtest_id: string;
    /**
     * Data
     */
    data: Array<BacktestEquityPointResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * BacktestMetricsSummary
 *
 * Summary of metrics from a single backtest run.
 */
export type BacktestMetricsSummary = {
    /**
     * Backtest Id
     */
    backtest_id: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Sharpe Ratio
     */
    sharpe_ratio: number | null;
    /**
     * Win Rate
     */
    win_rate: number | null;
    /**
     * Total Pnl
     */
    total_pnl: number | null;
    /**
     * Trade Count
     */
    trade_count: number | null;
    /**
     * Max Drawdown
     */
    max_drawdown: number | null;
    /**
     * Composite Score
     */
    composite_score: number | null;
};

/**
 * BacktestResponse
 *
 * Response model for a backtest record.
 */
export type BacktestResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Strategy Id
     */
    strategy_id: string | null;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    } | null;
    /**
     * Walk Forward
     */
    walk_forward: {
        [key: string]: unknown;
    } | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * BacktestRunRequest
 *
 * Request body for dispatching a backtest run.
 */
export type BacktestRunRequest = {
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Initial Capital
     */
    initial_capital?: number;
};

/**
 * BacktestTradeResponse
 *
 * Response model for a single backtest trade.
 */
export type BacktestTradeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Backtest Id
     */
    backtest_id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Action
     */
    action: string;
    /**
     * Entry Time
     */
    entry_time: string;
    /**
     * Exit Time
     */
    exit_time: string | null;
    /**
     * Entry Price
     */
    entry_price: number;
    /**
     * Exit Price
     */
    exit_price: number | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Pnl
     */
    pnl: number | null;
    /**
     * Fees
     */
    fees: number;
};

/**
 * CorrelationResponse
 */
export type CorrelationResponse = {
    /**
     * Symbols
     */
    symbols: Array<string>;
    /**
     * Matrix
     */
    matrix: Array<Array<number>>;
    /**
     * As Of
     */
    as_of?: string | null;
    /**
     * Computed At
     */
    computed_at?: string | null;
};

/**
 * ExperimentResponse
 *
 * Response for a single experiment record.
 */
export type ExperimentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Study Name
     */
    study_name: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Composite Score
     */
    composite_score: number;
    /**
     * Wfe Score
     */
    wfe_score: number;
    /**
     * Status
     */
    status: string;
    /**
     * Config Json
     */
    config_json: {
        [key: string]: unknown;
    };
    /**
     * Metrics Json
     */
    metrics_json: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ExposureItem
 */
export type ExposureItem = {
    /**
     * Category
     */
    category: string;
    /**
     * Value
     */
    value: number;
};

/**
 * ExposureResponse
 */
export type ExposureResponse = {
    /**
     * Exposures
     */
    exposures: Array<ExposureItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * FetchRequest
 *
 * Request body for triggering a data fetch.
 */
export type FetchRequest = {
    /**
     * Market
     */
    market: string;
    /**
     * Symbol
     */
    symbol?: string | null;
    /**
     * Interval
     */
    interval?: string;
};

/**
 * FundingRatePoint
 */
export type FundingRatePoint = {
    /**
     * Time
     */
    time: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Funding Rate
     */
    funding_rate: number;
    /**
     * Mark Price
     */
    mark_price: number | null;
    /**
     * Index Price
     */
    index_price: number | null;
};

/**
 * FundingRateResponse
 */
export type FundingRateResponse = {
    /**
     * Data
     */
    data: Array<FundingRatePoint>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HoldingResponse
 */
export type HoldingResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Weight
     */
    weight: number;
    /**
     * Shares
     */
    shares: number | null;
    /**
     * Entry Price
     */
    entry_price: number | null;
    /**
     * Entry Date
     */
    entry_date: string | null;
    /**
     * Stop Loss Pct
     */
    stop_loss_pct: number | null;
    /**
     * Current Price
     */
    current_price: number | null;
    /**
     * Unrealized Pnl
     */
    unrealized_pnl: number | null;
    /**
     * Side
     */
    side?: string;
};

/**
 * HoldingsResponse
 */
export type HoldingsResponse = {
    /**
     * Holdings
     */
    holdings: Array<HoldingResponse>;
    /**
     * Total Holdings
     */
    total_holdings: number;
};

/**
 * MarketSpecSchema
 *
 * A single market to search.
 */
export type MarketSpecSchema = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
};

/**
 * MessageResponse
 *
 * Generic message response.
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Task Id
     */
    task_id?: string | null;
};

/**
 * ModelVersionResponse
 *
 * Response model for a model version.
 */
export type ModelVersionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: number;
    /**
     * Status
     */
    status: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    } | null;
    /**
     * Feature List
     */
    feature_list: Array<unknown>;
    /**
     * Train Start
     */
    train_start: string | null;
    /**
     * Train End
     */
    train_end: string | null;
    /**
     * Artifact Path
     */
    artifact_path: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Message
     */
    error_message: string | null;
};

/**
 * NavPointResponse
 */
export type NavPointResponse = {
    /**
     * Date
     */
    date: string;
    /**
     * Total Nav
     */
    total_nav: number;
    /**
     * Holdings Value
     */
    holdings_value: number;
    /**
     * Cash
     */
    cash: number;
    /**
     * Holdings Count
     */
    holdings_count: number;
};

/**
 * NotificationItem
 */
export type NotificationItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Timestamp
     */
    timestamp?: string | null;
};

/**
 * NotificationsResponse
 */
export type NotificationsResponse = {
    /**
     * Notifications
     */
    notifications: Array<NotificationItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * OHLCVPoint
 */
export type OhlcvPoint = {
    /**
     * Time
     */
    time: string;
    /**
     * Open
     */
    open: number;
    /**
     * High
     */
    high: number;
    /**
     * Low
     */
    low: number;
    /**
     * Close
     */
    close: number;
    /**
     * Volume
     */
    volume: number;
};

/**
 * OHLCVResponse
 */
export type OhlcvResponse = {
    /**
     * Data
     */
    data: Array<OhlcvPoint>;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Count
     */
    count: number;
};

/**
 * OptimizeRequest
 *
 * Request body for dispatching a parameter optimization.
 */
export type OptimizeRequest = {
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Param Grid
     */
    param_grid: {
        [key: string]: unknown;
    };
    /**
     * Method
     */
    method?: string;
    /**
     * N Trials
     */
    n_trials?: number;
    /**
     * Target Metric
     */
    target_metric?: string;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * OrderResponse
 */
export type OrderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Action
     */
    action: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Status
     */
    status: string;
    /**
     * Price
     */
    price: number | null;
    /**
     * Broker Mode
     */
    broker_mode: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Side
     */
    side?: string;
};

/**
 * OrdersResponse
 */
export type OrdersResponse = {
    /**
     * Orders
     */
    orders: Array<OrderResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * PerformanceSummaryResponse
 */
export type PerformanceSummaryResponse = {
    /**
     * Nav Curve
     */
    nav_curve: Array<NavPointResponse>;
    /**
     * Total Return Pct
     */
    total_return_pct: number;
    /**
     * Max Drawdown Pct
     */
    max_drawdown_pct: number;
    /**
     * Sharpe Ratio
     */
    sharpe_ratio: number | null;
    /**
     * Total Trades
     */
    total_trades: number;
    /**
     * Total Realized Pnl
     */
    total_realized_pnl: number;
};

/**
 * PerpHoldingResponse
 */
export type PerpHoldingResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Side
     */
    side: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Entry Price
     */
    entry_price: number;
    /**
     * Leverage
     */
    leverage: number;
    /**
     * Liquidation Price
     */
    liquidation_price: number;
    /**
     * Margin Ratio
     */
    margin_ratio: number;
    /**
     * Unrealized Pnl
     */
    unrealized_pnl: number;
    /**
     * Cumulative Funding Cost
     */
    cumulative_funding_cost: number;
    /**
     * Current Price
     */
    current_price?: number | null;
};

/**
 * PerpHoldingsResponse
 */
export type PerpHoldingsResponse = {
    /**
     * Holdings
     */
    holdings: Array<PerpHoldingResponse>;
    /**
     * Total Holdings
     */
    total_holdings: number;
};

/**
 * PredictRequest
 *
 * Request body for model prediction.
 */
export type PredictRequest = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Use Latest Data
     */
    use_latest_data?: boolean;
};

/**
 * QualityScoreResponse
 */
export type QualityScoreResponse = {
    /**
     * Time
     */
    time: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Score
     */
    score: number;
    /**
     * Completeness
     */
    completeness: number;
    /**
     * Consistency
     */
    consistency: number;
    /**
     * Anomaly Free
     */
    anomaly_free: number;
    /**
     * Timeliness
     */
    timeliness: number;
};

/**
 * QualityScoresResponse
 */
export type QualityScoresResponse = {
    /**
     * Scores
     */
    scores: Array<QualityScoreResponse>;
};

/**
 * RiskRuleCreate
 *
 * Request body for creating a new risk rule.
 */
export type RiskRuleCreate = {
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Priority
     */
    priority?: number;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * RiskRuleResponse
 *
 * Response model for a risk rule.
 */
export type RiskRuleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Priority
     */
    priority: number;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RiskRuleUpdate
 *
 * Request body for updating an existing risk rule.
 *
 * Only provided (non-None) fields are applied.
 */
export type RiskRuleUpdate = {
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
};

/**
 * SentimentCreate
 *
 * Request body for creating a sentiment score.
 */
export type SentimentCreate = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Score
     */
    score: number;
};

/**
 * SentimentResponse
 *
 * Response body for a sentiment score.
 */
export type SentimentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Score
     */
    score: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SignalResponse
 *
 * Response model for a signal record.
 */
export type SignalResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Strategy Id
     */
    strategy_id: string | null;
    /**
     * Model Id
     */
    model_id: string | null;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Instrument
     */
    instrument: string;
    /**
     * Action
     */
    action: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Quantity Pct
     */
    quantity_pct: number | null;
    /**
     * Signal Time
     */
    signal_time: string;
    /**
     * Valid Until
     */
    valid_until: string | null;
    /**
     * Interval
     */
    interval: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * StrategyCreate
 *
 * Request body for creating a new strategy.
 */
export type StrategyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Model Version Id
     */
    model_version_id?: string | null;
};

/**
 * StrategyPerformanceResponse
 *
 * Aggregated performance response: best + latest backtest metrics.
 */
export type StrategyPerformanceResponse = {
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Backtest Count
     */
    backtest_count: number;
    best: BacktestMetricsSummary | null;
    latest: BacktestMetricsSummary | null;
};

/**
 * StrategyResponse
 *
 * Response model for a strategy.
 */
export type StrategyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Strategy Type
     */
    strategy_type: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Model Version Id
     */
    model_version_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * StrategyUpdate
 *
 * Request body for updating an existing strategy.
 *
 * Only provided (non-None) fields are applied.
 */
export type StrategyUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Symbol
     */
    symbol?: string | null;
    /**
     * Market
     */
    market?: string | null;
    /**
     * Interval
     */
    interval?: string | null;
    /**
     * Model Version Id
     */
    model_version_id?: string | null;
};

/**
 * StressTestRequest
 */
export type StressTestRequest = {
    /**
     * Scenario Name
     */
    scenario_name: string;
    /**
     * Custom Shocks
     */
    custom_shocks?: {
        [key: string]: number;
    } | null;
};

/**
 * StressTestStatusResponse
 */
export type StressTestStatusResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * StressTestTriggerResponse
 */
export type StressTestTriggerResponse = {
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * TaskStatusResponse
 *
 * Response for task status polling.
 */
export type TaskStatusResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress?: {
        [key: string]: unknown;
    } | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * TrainRequest
 *
 * Request body for dispatching a model training job.
 */
export type TrainRequest = {
    /**
     * Model Name
     */
    model_name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Interval
     */
    interval?: string;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
    /**
     * Feature List
     */
    feature_list?: Array<string>;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Label Mode
     */
    label_mode?: string;
};

/**
 * TransitionRequest
 *
 * Optional body for lifecycle transitions (e.g. attach metrics).
 */
export type TransitionRequest = {
    /**
     * Metrics
     */
    metrics?: {
        [key: string]: unknown;
    } | null;
};

/**
 * VaRResponse
 */
export type VaRResponse = {
    /**
     * Snapshots
     */
    snapshots: Array<VaRSnapshotResponse>;
};

/**
 * VaRSnapshotResponse
 */
export type VaRSnapshotResponse = {
    /**
     * Method
     */
    method: string;
    /**
     * Var 95
     */
    var_95: number;
    /**
     * Var 99
     */
    var_99: number;
    /**
     * Cvar 95
     */
    cvar_95: number;
    /**
     * Cvar 99
     */
    cvar_99: number;
    /**
     * Portfolio Value
     */
    portfolio_value: number;
    /**
     * Holding Period
     */
    holding_period: number;
    /**
     * As Of
     */
    as_of?: string | null;
    /**
     * Computed At
     */
    computed_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VirtualPositionResponse
 *
 * Response model for a virtual portfolio position.
 */
export type VirtualPositionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Market
     */
    market: string;
    /**
     * Instrument
     */
    instrument: string;
    /**
     * Side
     */
    side: string;
    /**
     * Quantity Pct
     */
    quantity_pct: number;
    /**
     * Entry Time
     */
    entry_time: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerFetchApiDataFetchPostData = {
    body: FetchRequest;
    path?: never;
    query?: never;
    url: '/api/data/fetch';
};

export type TriggerFetchApiDataFetchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerFetchApiDataFetchPostError = TriggerFetchApiDataFetchPostErrors[keyof TriggerFetchApiDataFetchPostErrors];

export type TriggerFetchApiDataFetchPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type TriggerFetchApiDataFetchPostResponse = TriggerFetchApiDataFetchPostResponses[keyof TriggerFetchApiDataFetchPostResponses];

export type TriggerBackfillEndpointApiDataBackfillPostData = {
    body: BackfillRequest;
    path?: never;
    query?: never;
    url: '/api/data/backfill';
};

export type TriggerBackfillEndpointApiDataBackfillPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerBackfillEndpointApiDataBackfillPostError = TriggerBackfillEndpointApiDataBackfillPostErrors[keyof TriggerBackfillEndpointApiDataBackfillPostErrors];

export type TriggerBackfillEndpointApiDataBackfillPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type TriggerBackfillEndpointApiDataBackfillPostResponse = TriggerBackfillEndpointApiDataBackfillPostResponses[keyof TriggerBackfillEndpointApiDataBackfillPostResponses];

export type GetBackfillStatusApiDataBackfillStatusGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
    };
    url: '/api/data/backfill/status';
};

export type GetBackfillStatusApiDataBackfillStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBackfillStatusApiDataBackfillStatusGetError = GetBackfillStatusApiDataBackfillStatusGetErrors[keyof GetBackfillStatusApiDataBackfillStatusGetErrors];

export type GetBackfillStatusApiDataBackfillStatusGetResponses = {
    /**
     * Response Get Backfill Status Api Data Backfill Status Get
     *
     * Successful Response
     */
    200: Array<BackfillStatusResponse>;
};

export type GetBackfillStatusApiDataBackfillStatusGetResponse = GetBackfillStatusApiDataBackfillStatusGetResponses[keyof GetBackfillStatusApiDataBackfillStatusGetResponses];

export type GetOhlcvApiDataOhlcvGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Symbol
         *
         * Ticker symbol, e.g. BTCUSDT
         */
        symbol: string;
        /**
         * Market
         *
         * Market name, e.g. crypto_perp
         */
        market: string;
        /**
         * Interval
         *
         * Candle interval, e.g. 1d, 4h, 1h
         */
        interval?: string;
        /**
         * Start
         *
         * Start date (ISO format)
         */
        start?: string | null;
        /**
         * End
         *
         * End date (ISO format)
         */
        end?: string | null;
    };
    url: '/api/data/ohlcv';
};

export type GetOhlcvApiDataOhlcvGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOhlcvApiDataOhlcvGetError = GetOhlcvApiDataOhlcvGetErrors[keyof GetOhlcvApiDataOhlcvGetErrors];

export type GetOhlcvApiDataOhlcvGetResponses = {
    /**
     * Successful Response
     */
    200: OhlcvResponse;
};

export type GetOhlcvApiDataOhlcvGetResponse = GetOhlcvApiDataOhlcvGetResponses[keyof GetOhlcvApiDataOhlcvGetResponses];

export type GetFundingRatesApiDataFundingRatesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Symbol
         *
         * Perp symbol, e.g. BTC/USDT:USDT
         */
        symbol: string;
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/data/funding-rates';
};

export type GetFundingRatesApiDataFundingRatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFundingRatesApiDataFundingRatesGetError = GetFundingRatesApiDataFundingRatesGetErrors[keyof GetFundingRatesApiDataFundingRatesGetErrors];

export type GetFundingRatesApiDataFundingRatesGetResponses = {
    /**
     * Successful Response
     */
    200: FundingRateResponse;
};

export type GetFundingRatesApiDataFundingRatesGetResponse = GetFundingRatesApiDataFundingRatesGetResponses[keyof GetFundingRatesApiDataFundingRatesGetResponses];

export type ListSentimentApiSentimentGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Symbol
         *
         * Symbol to query sentiment for
         */
        symbol: string;
        /**
         * Market
         *
         * Optional market filter
         */
        market?: string | null;
        /**
         * Limit
         *
         * Max results to return
         */
        limit?: number;
    };
    url: '/api/sentiment';
};

export type ListSentimentApiSentimentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSentimentApiSentimentGetError = ListSentimentApiSentimentGetErrors[keyof ListSentimentApiSentimentGetErrors];

export type ListSentimentApiSentimentGetResponses = {
    /**
     * Response List Sentiment Api Sentiment Get
     *
     * Successful Response
     */
    200: Array<SentimentResponse>;
};

export type ListSentimentApiSentimentGetResponse = ListSentimentApiSentimentGetResponses[keyof ListSentimentApiSentimentGetResponses];

export type CreateSentimentApiSentimentPostData = {
    body: SentimentCreate;
    path?: never;
    query?: never;
    url: '/api/sentiment';
};

export type CreateSentimentApiSentimentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSentimentApiSentimentPostError = CreateSentimentApiSentimentPostErrors[keyof CreateSentimentApiSentimentPostErrors];

export type CreateSentimentApiSentimentPostResponses = {
    /**
     * Successful Response
     */
    201: SentimentResponse;
};

export type CreateSentimentApiSentimentPostResponse = CreateSentimentApiSentimentPostResponses[keyof CreateSentimentApiSentimentPostResponses];

export type ListRuleTypesApiRiskRulesTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk-rules/types';
};

export type ListRuleTypesApiRiskRulesTypesGetResponses = {
    /**
     * Response List Rule Types Api Risk Rules Types Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListRuleTypesApiRiskRulesTypesGetResponse = ListRuleTypesApiRiskRulesTypesGetResponses[keyof ListRuleTypesApiRiskRulesTypesGetResponses];

export type ListRulesApiRiskRulesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk-rules';
};

export type ListRulesApiRiskRulesGetResponses = {
    /**
     * Response List Rules Api Risk Rules Get
     *
     * Successful Response
     */
    200: Array<RiskRuleResponse>;
};

export type ListRulesApiRiskRulesGetResponse = ListRulesApiRiskRulesGetResponses[keyof ListRulesApiRiskRulesGetResponses];

export type CreateRuleApiRiskRulesPostData = {
    body: RiskRuleCreate;
    path?: never;
    query?: never;
    url: '/api/risk-rules';
};

export type CreateRuleApiRiskRulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRuleApiRiskRulesPostError = CreateRuleApiRiskRulesPostErrors[keyof CreateRuleApiRiskRulesPostErrors];

export type CreateRuleApiRiskRulesPostResponses = {
    /**
     * Successful Response
     */
    201: RiskRuleResponse;
};

export type CreateRuleApiRiskRulesPostResponse = CreateRuleApiRiskRulesPostResponses[keyof CreateRuleApiRiskRulesPostResponses];

export type GetPortfolioApiRiskRulesPortfolioGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
    };
    url: '/api/risk-rules/portfolio';
};

export type GetPortfolioApiRiskRulesPortfolioGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPortfolioApiRiskRulesPortfolioGetError = GetPortfolioApiRiskRulesPortfolioGetErrors[keyof GetPortfolioApiRiskRulesPortfolioGetErrors];

export type GetPortfolioApiRiskRulesPortfolioGetResponses = {
    /**
     * Response Get Portfolio Api Risk Rules Portfolio Get
     *
     * Successful Response
     */
    200: Array<VirtualPositionResponse>;
};

export type GetPortfolioApiRiskRulesPortfolioGetResponse = GetPortfolioApiRiskRulesPortfolioGetResponses[keyof GetPortfolioApiRiskRulesPortfolioGetResponses];

export type DeleteRuleApiRiskRulesRuleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type DeleteRuleApiRiskRulesRuleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRuleApiRiskRulesRuleIdDeleteError = DeleteRuleApiRiskRulesRuleIdDeleteErrors[keyof DeleteRuleApiRiskRulesRuleIdDeleteErrors];

export type DeleteRuleApiRiskRulesRuleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRuleApiRiskRulesRuleIdDeleteResponse = DeleteRuleApiRiskRulesRuleIdDeleteResponses[keyof DeleteRuleApiRiskRulesRuleIdDeleteResponses];

export type GetRuleApiRiskRulesRuleIdGetData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type GetRuleApiRiskRulesRuleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleApiRiskRulesRuleIdGetError = GetRuleApiRiskRulesRuleIdGetErrors[keyof GetRuleApiRiskRulesRuleIdGetErrors];

export type GetRuleApiRiskRulesRuleIdGetResponses = {
    /**
     * Successful Response
     */
    200: RiskRuleResponse;
};

export type GetRuleApiRiskRulesRuleIdGetResponse = GetRuleApiRiskRulesRuleIdGetResponses[keyof GetRuleApiRiskRulesRuleIdGetResponses];

export type UpdateRuleApiRiskRulesRuleIdPatchData = {
    body: RiskRuleUpdate;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/risk-rules/{rule_id}';
};

export type UpdateRuleApiRiskRulesRuleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRuleApiRiskRulesRuleIdPatchError = UpdateRuleApiRiskRulesRuleIdPatchErrors[keyof UpdateRuleApiRiskRulesRuleIdPatchErrors];

export type UpdateRuleApiRiskRulesRuleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RiskRuleResponse;
};

export type UpdateRuleApiRiskRulesRuleIdPatchResponse = UpdateRuleApiRiskRulesRuleIdPatchResponses[keyof UpdateRuleApiRiskRulesRuleIdPatchResponses];

export type ListStrategiesApiStrategiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/strategies';
};

export type ListStrategiesApiStrategiesGetResponses = {
    /**
     * Response List Strategies Api Strategies Get
     *
     * Successful Response
     */
    200: Array<StrategyResponse>;
};

export type ListStrategiesApiStrategiesGetResponse = ListStrategiesApiStrategiesGetResponses[keyof ListStrategiesApiStrategiesGetResponses];

export type CreateStrategyApiStrategiesPostData = {
    body: StrategyCreate;
    path?: never;
    query?: never;
    url: '/api/strategies';
};

export type CreateStrategyApiStrategiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStrategyApiStrategiesPostError = CreateStrategyApiStrategiesPostErrors[keyof CreateStrategyApiStrategiesPostErrors];

export type CreateStrategyApiStrategiesPostResponses = {
    /**
     * Successful Response
     */
    201: StrategyResponse;
};

export type CreateStrategyApiStrategiesPostResponse = CreateStrategyApiStrategiesPostResponses[keyof CreateStrategyApiStrategiesPostResponses];

export type DeleteStrategyApiStrategiesStrategyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}';
};

export type DeleteStrategyApiStrategiesStrategyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStrategyApiStrategiesStrategyIdDeleteError = DeleteStrategyApiStrategiesStrategyIdDeleteErrors[keyof DeleteStrategyApiStrategiesStrategyIdDeleteErrors];

export type DeleteStrategyApiStrategiesStrategyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteStrategyApiStrategiesStrategyIdDeleteResponse = DeleteStrategyApiStrategiesStrategyIdDeleteResponses[keyof DeleteStrategyApiStrategiesStrategyIdDeleteResponses];

export type GetStrategyApiStrategiesStrategyIdGetData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}';
};

export type GetStrategyApiStrategiesStrategyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStrategyApiStrategiesStrategyIdGetError = GetStrategyApiStrategiesStrategyIdGetErrors[keyof GetStrategyApiStrategiesStrategyIdGetErrors];

export type GetStrategyApiStrategiesStrategyIdGetResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type GetStrategyApiStrategiesStrategyIdGetResponse = GetStrategyApiStrategiesStrategyIdGetResponses[keyof GetStrategyApiStrategiesStrategyIdGetResponses];

export type UpdateStrategyApiStrategiesStrategyIdPutData = {
    body: StrategyUpdate;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}';
};

export type UpdateStrategyApiStrategiesStrategyIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStrategyApiStrategiesStrategyIdPutError = UpdateStrategyApiStrategiesStrategyIdPutErrors[keyof UpdateStrategyApiStrategiesStrategyIdPutErrors];

export type UpdateStrategyApiStrategiesStrategyIdPutResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type UpdateStrategyApiStrategiesStrategyIdPutResponse = UpdateStrategyApiStrategiesStrategyIdPutResponses[keyof UpdateStrategyApiStrategiesStrategyIdPutResponses];

export type ActivateStrategyApiStrategiesStrategyIdActivatePostData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}/activate';
};

export type ActivateStrategyApiStrategiesStrategyIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateStrategyApiStrategiesStrategyIdActivatePostError = ActivateStrategyApiStrategiesStrategyIdActivatePostErrors[keyof ActivateStrategyApiStrategiesStrategyIdActivatePostErrors];

export type ActivateStrategyApiStrategiesStrategyIdActivatePostResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type ActivateStrategyApiStrategiesStrategyIdActivatePostResponse = ActivateStrategyApiStrategiesStrategyIdActivatePostResponses[keyof ActivateStrategyApiStrategiesStrategyIdActivatePostResponses];

export type DeactivateStrategyApiStrategiesStrategyIdDeactivatePostData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}/deactivate';
};

export type DeactivateStrategyApiStrategiesStrategyIdDeactivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateStrategyApiStrategiesStrategyIdDeactivatePostError = DeactivateStrategyApiStrategiesStrategyIdDeactivatePostErrors[keyof DeactivateStrategyApiStrategiesStrategyIdDeactivatePostErrors];

export type DeactivateStrategyApiStrategiesStrategyIdDeactivatePostResponses = {
    /**
     * Successful Response
     */
    200: StrategyResponse;
};

export type DeactivateStrategyApiStrategiesStrategyIdDeactivatePostResponse = DeactivateStrategyApiStrategiesStrategyIdDeactivatePostResponses[keyof DeactivateStrategyApiStrategiesStrategyIdDeactivatePostResponses];

export type GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetData = {
    body?: never;
    path: {
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/strategies/{strategy_id}/performance';
};

export type GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetError = GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetErrors[keyof GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetErrors];

export type GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetResponses = {
    /**
     * Successful Response
     */
    200: StrategyPerformanceResponse;
};

export type GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetResponse = GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetResponses[keyof GetStrategyPerformanceApiStrategiesStrategyIdPerformanceGetResponses];

export type StartTrainingApiModelsTrainPostData = {
    body: TrainRequest;
    path?: never;
    query?: never;
    url: '/api/models/train';
};

export type StartTrainingApiModelsTrainPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartTrainingApiModelsTrainPostError = StartTrainingApiModelsTrainPostErrors[keyof StartTrainingApiModelsTrainPostErrors];

export type StartTrainingApiModelsTrainPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type StartTrainingApiModelsTrainPostResponse = StartTrainingApiModelsTrainPostResponses[keyof StartTrainingApiModelsTrainPostResponses];

export type ListModelsApiModelsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/api/models';
};

export type ListModelsApiModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsApiModelsGetError = ListModelsApiModelsGetErrors[keyof ListModelsApiModelsGetErrors];

export type ListModelsApiModelsGetResponses = {
    /**
     * Response List Models Api Models Get
     *
     * Successful Response
     */
    200: Array<ModelVersionResponse>;
};

export type ListModelsApiModelsGetResponse = ListModelsApiModelsGetResponses[keyof ListModelsApiModelsGetResponses];

export type GetModelVersionApiModelsVersionIdGetData = {
    body?: never;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/models/{version_id}';
};

export type GetModelVersionApiModelsVersionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelVersionApiModelsVersionIdGetError = GetModelVersionApiModelsVersionIdGetErrors[keyof GetModelVersionApiModelsVersionIdGetErrors];

export type GetModelVersionApiModelsVersionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type GetModelVersionApiModelsVersionIdGetResponse = GetModelVersionApiModelsVersionIdGetResponses[keyof GetModelVersionApiModelsVersionIdGetResponses];

export type ShadowModelApiModelsVersionIdShadowPostData = {
    /**
     * Body
     */
    body?: TransitionRequest | null;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/models/{version_id}/shadow';
};

export type ShadowModelApiModelsVersionIdShadowPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShadowModelApiModelsVersionIdShadowPostError = ShadowModelApiModelsVersionIdShadowPostErrors[keyof ShadowModelApiModelsVersionIdShadowPostErrors];

export type ShadowModelApiModelsVersionIdShadowPostResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type ShadowModelApiModelsVersionIdShadowPostResponse = ShadowModelApiModelsVersionIdShadowPostResponses[keyof ShadowModelApiModelsVersionIdShadowPostResponses];

export type ActivateModelApiModelsVersionIdActivatePostData = {
    /**
     * Body
     */
    body?: TransitionRequest | null;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/models/{version_id}/activate';
};

export type ActivateModelApiModelsVersionIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateModelApiModelsVersionIdActivatePostError = ActivateModelApiModelsVersionIdActivatePostErrors[keyof ActivateModelApiModelsVersionIdActivatePostErrors];

export type ActivateModelApiModelsVersionIdActivatePostResponses = {
    /**
     * Successful Response
     */
    200: ModelVersionResponse;
};

export type ActivateModelApiModelsVersionIdActivatePostResponse = ActivateModelApiModelsVersionIdActivatePostResponses[keyof ActivateModelApiModelsVersionIdActivatePostResponses];

export type PredictApiModelsVersionIdPredictPostData = {
    body: PredictRequest;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/models/{version_id}/predict';
};

export type PredictApiModelsVersionIdPredictPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PredictApiModelsVersionIdPredictPostError = PredictApiModelsVersionIdPredictPostErrors[keyof PredictApiModelsVersionIdPredictPostErrors];

export type PredictApiModelsVersionIdPredictPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type PredictApiModelsVersionIdPredictPostResponse = PredictApiModelsVersionIdPredictPostResponses[keyof PredictApiModelsVersionIdPredictPostResponses];

export type RunBacktestApiBacktestRunPostData = {
    body: BacktestRunRequest;
    path?: never;
    query?: never;
    url: '/api/backtest/run';
};

export type RunBacktestApiBacktestRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunBacktestApiBacktestRunPostError = RunBacktestApiBacktestRunPostErrors[keyof RunBacktestApiBacktestRunPostErrors];

export type RunBacktestApiBacktestRunPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunBacktestApiBacktestRunPostResponse = RunBacktestApiBacktestRunPostResponses[keyof RunBacktestApiBacktestRunPostResponses];

export type RunOptimizationApiBacktestOptimizePostData = {
    body: OptimizeRequest;
    path?: never;
    query?: never;
    url: '/api/backtest/optimize';
};

export type RunOptimizationApiBacktestOptimizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunOptimizationApiBacktestOptimizePostError = RunOptimizationApiBacktestOptimizePostErrors[keyof RunOptimizationApiBacktestOptimizePostErrors];

export type RunOptimizationApiBacktestOptimizePostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunOptimizationApiBacktestOptimizePostResponse = RunOptimizationApiBacktestOptimizePostResponses[keyof RunOptimizationApiBacktestOptimizePostResponses];

export type ListBacktestsApiBacktestGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Strategy Id
         */
        strategy_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/backtest';
};

export type ListBacktestsApiBacktestGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBacktestsApiBacktestGetError = ListBacktestsApiBacktestGetErrors[keyof ListBacktestsApiBacktestGetErrors];

export type ListBacktestsApiBacktestGetResponses = {
    /**
     * Response List Backtests Api Backtest Get
     *
     * Successful Response
     */
    200: Array<BacktestResponse>;
};

export type ListBacktestsApiBacktestGetResponse = ListBacktestsApiBacktestGetResponses[keyof ListBacktestsApiBacktestGetResponses];

export type GetBacktestApiBacktestBacktestIdGetData = {
    body?: never;
    path: {
        /**
         * Backtest Id
         */
        backtest_id: string;
    };
    query?: never;
    url: '/api/backtest/{backtest_id}';
};

export type GetBacktestApiBacktestBacktestIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBacktestApiBacktestBacktestIdGetError = GetBacktestApiBacktestBacktestIdGetErrors[keyof GetBacktestApiBacktestBacktestIdGetErrors];

export type GetBacktestApiBacktestBacktestIdGetResponses = {
    /**
     * Successful Response
     */
    200: BacktestResponse;
};

export type GetBacktestApiBacktestBacktestIdGetResponse = GetBacktestApiBacktestBacktestIdGetResponses[keyof GetBacktestApiBacktestBacktestIdGetResponses];

export type GetBacktestTradesApiBacktestBacktestIdTradesGetData = {
    body?: never;
    path: {
        /**
         * Backtest Id
         */
        backtest_id: string;
    };
    query?: never;
    url: '/api/backtest/{backtest_id}/trades';
};

export type GetBacktestTradesApiBacktestBacktestIdTradesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBacktestTradesApiBacktestBacktestIdTradesGetError = GetBacktestTradesApiBacktestBacktestIdTradesGetErrors[keyof GetBacktestTradesApiBacktestBacktestIdTradesGetErrors];

export type GetBacktestTradesApiBacktestBacktestIdTradesGetResponses = {
    /**
     * Response Get Backtest Trades Api Backtest  Backtest Id  Trades Get
     *
     * Successful Response
     */
    200: Array<BacktestTradeResponse>;
};

export type GetBacktestTradesApiBacktestBacktestIdTradesGetResponse = GetBacktestTradesApiBacktestBacktestIdTradesGetResponses[keyof GetBacktestTradesApiBacktestBacktestIdTradesGetResponses];

export type GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetData = {
    body?: never;
    path: {
        /**
         * Backtest Id
         */
        backtest_id: string;
    };
    query?: never;
    url: '/api/backtest/{backtest_id}/equity-curve';
};

export type GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetError = GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetErrors[keyof GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetErrors];

export type GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetResponses = {
    /**
     * Successful Response
     */
    200: BacktestEquityResponse;
};

export type GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetResponse = GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetResponses[keyof GetBacktestEquityCurveApiBacktestBacktestIdEquityCurveGetResponses];

export type ListSignalsApiSignalsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         */
        market?: string | null;
        /**
         * Symbol
         */
        symbol?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/signals';
};

export type ListSignalsApiSignalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSignalsApiSignalsGetError = ListSignalsApiSignalsGetErrors[keyof ListSignalsApiSignalsGetErrors];

export type ListSignalsApiSignalsGetResponses = {
    /**
     * Response List Signals Api Signals Get
     *
     * Successful Response
     */
    200: Array<SignalResponse>;
};

export type ListSignalsApiSignalsGetResponse = ListSignalsApiSignalsGetResponses[keyof ListSignalsApiSignalsGetResponses];

export type GetSignalApiSignalsSignalIdGetData = {
    body?: never;
    path: {
        /**
         * Signal Id
         */
        signal_id: string;
    };
    query?: never;
    url: '/api/signals/{signal_id}';
};

export type GetSignalApiSignalsSignalIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSignalApiSignalsSignalIdGetError = GetSignalApiSignalsSignalIdGetErrors[keyof GetSignalApiSignalsSignalIdGetErrors];

export type GetSignalApiSignalsSignalIdGetResponses = {
    /**
     * Successful Response
     */
    200: SignalResponse;
};

export type GetSignalApiSignalsSignalIdGetResponse = GetSignalApiSignalsSignalIdGetResponses[keyof GetSignalApiSignalsSignalIdGetResponses];

export type RunAutoresearchApiAutoresearchRunPostData = {
    body: AutoResearchRequest;
    path?: never;
    query?: never;
    url: '/api/autoresearch/run';
};

export type RunAutoresearchApiAutoresearchRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunAutoresearchApiAutoresearchRunPostError = RunAutoresearchApiAutoresearchRunPostErrors[keyof RunAutoresearchApiAutoresearchRunPostErrors];

export type RunAutoresearchApiAutoresearchRunPostResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type RunAutoresearchApiAutoresearchRunPostResponse = RunAutoresearchApiAutoresearchRunPostResponses[keyof RunAutoresearchApiAutoresearchRunPostResponses];

export type GetTaskStatusApiAutoresearchStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/autoresearch/status/{task_id}';
};

export type GetTaskStatusApiAutoresearchStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskStatusApiAutoresearchStatusTaskIdGetError = GetTaskStatusApiAutoresearchStatusTaskIdGetErrors[keyof GetTaskStatusApiAutoresearchStatusTaskIdGetErrors];

export type GetTaskStatusApiAutoresearchStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskStatusResponse;
};

export type GetTaskStatusApiAutoresearchStatusTaskIdGetResponse = GetTaskStatusApiAutoresearchStatusTaskIdGetResponses[keyof GetTaskStatusApiAutoresearchStatusTaskIdGetResponses];

export type StopAutoresearchApiAutoresearchStopTaskIdPostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/autoresearch/stop/{task_id}';
};

export type StopAutoresearchApiAutoresearchStopTaskIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopAutoresearchApiAutoresearchStopTaskIdPostError = StopAutoresearchApiAutoresearchStopTaskIdPostErrors[keyof StopAutoresearchApiAutoresearchStopTaskIdPostErrors];

export type StopAutoresearchApiAutoresearchStopTaskIdPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type StopAutoresearchApiAutoresearchStopTaskIdPostResponse = StopAutoresearchApiAutoresearchStopTaskIdPostResponses[keyof StopAutoresearchApiAutoresearchStopTaskIdPostResponses];

export type ListExperimentsApiAutoresearchExperimentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Study Name
         */
        study_name?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/autoresearch/experiments';
};

export type ListExperimentsApiAutoresearchExperimentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExperimentsApiAutoresearchExperimentsGetError = ListExperimentsApiAutoresearchExperimentsGetErrors[keyof ListExperimentsApiAutoresearchExperimentsGetErrors];

export type ListExperimentsApiAutoresearchExperimentsGetResponses = {
    /**
     * Response List Experiments Api Autoresearch Experiments Get
     *
     * Successful Response
     */
    200: Array<ExperimentResponse>;
};

export type ListExperimentsApiAutoresearchExperimentsGetResponse = ListExperimentsApiAutoresearchExperimentsGetResponses[keyof ListExperimentsApiAutoresearchExperimentsGetResponses];

export type GetProviderHealthApiDataQualityProvidersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/data-quality/providers';
};

export type GetProviderHealthApiDataQualityProvidersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQualityScoresApiDataQualityScoresGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Symbol
         *
         * Filter by symbol
         */
        symbol?: string | null;
        /**
         * Interval
         *
         * Filter by interval
         */
        interval?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/data-quality/scores';
};

export type GetQualityScoresApiDataQualityScoresGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQualityScoresApiDataQualityScoresGetError = GetQualityScoresApiDataQualityScoresGetErrors[keyof GetQualityScoresApiDataQualityScoresGetErrors];

export type GetQualityScoresApiDataQualityScoresGetResponses = {
    /**
     * Successful Response
     */
    200: QualityScoresResponse;
};

export type GetQualityScoresApiDataQualityScoresGetResponse = GetQualityScoresApiDataQualityScoresGetResponses[keyof GetQualityScoresApiDataQualityScoresGetResponses];

export type GetVarApiRiskVarGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk/var';
};

export type GetVarApiRiskVarGetResponses = {
    /**
     * Successful Response
     */
    200: VaRResponse;
};

export type GetVarApiRiskVarGetResponse = GetVarApiRiskVarGetResponses[keyof GetVarApiRiskVarGetResponses];

export type GetExposureApiRiskExposureGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk/exposure';
};

export type GetExposureApiRiskExposureGetResponses = {
    /**
     * Successful Response
     */
    200: ExposureResponse;
};

export type GetExposureApiRiskExposureGetResponse = GetExposureApiRiskExposureGetResponses[keyof GetExposureApiRiskExposureGetResponses];

export type TriggerStressTestApiRiskStressTestRunPostData = {
    body: StressTestRequest;
    path?: never;
    query?: never;
    url: '/api/risk/stress-test/run';
};

export type TriggerStressTestApiRiskStressTestRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerStressTestApiRiskStressTestRunPostError = TriggerStressTestApiRiskStressTestRunPostErrors[keyof TriggerStressTestApiRiskStressTestRunPostErrors];

export type TriggerStressTestApiRiskStressTestRunPostResponses = {
    /**
     * Successful Response
     */
    200: StressTestTriggerResponse;
};

export type TriggerStressTestApiRiskStressTestRunPostResponse = TriggerStressTestApiRiskStressTestRunPostResponses[keyof TriggerStressTestApiRiskStressTestRunPostResponses];

export type GetStressTestResultApiRiskStressTestTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/risk/stress-test/{task_id}';
};

export type GetStressTestResultApiRiskStressTestTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStressTestResultApiRiskStressTestTaskIdGetError = GetStressTestResultApiRiskStressTestTaskIdGetErrors[keyof GetStressTestResultApiRiskStressTestTaskIdGetErrors];

export type GetStressTestResultApiRiskStressTestTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: StressTestStatusResponse;
};

export type GetStressTestResultApiRiskStressTestTaskIdGetResponse = GetStressTestResultApiRiskStressTestTaskIdGetResponses[keyof GetStressTestResultApiRiskStressTestTaskIdGetResponses];

export type GetAlertsApiRiskAlertsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/risk/alerts';
};

export type GetAlertsApiRiskAlertsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlertsApiRiskAlertsGetError = GetAlertsApiRiskAlertsGetErrors[keyof GetAlertsApiRiskAlertsGetErrors];

export type GetAlertsApiRiskAlertsGetResponses = {
    /**
     * Successful Response
     */
    200: AlertsResponse;
};

export type GetAlertsApiRiskAlertsGetResponse = GetAlertsApiRiskAlertsGetResponses[keyof GetAlertsApiRiskAlertsGetResponses];

export type GetCorrelationApiRiskCorrelationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/risk/correlation';
};

export type GetCorrelationApiRiskCorrelationGetResponses = {
    /**
     * Successful Response
     */
    200: CorrelationResponse;
};

export type GetCorrelationApiRiskCorrelationGetResponse = GetCorrelationApiRiskCorrelationGetResponses[keyof GetCorrelationApiRiskCorrelationGetResponses];

export type GetPerformanceApiPortfolioPerformanceGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Market
         *
         * Filter by market (e.g., 'crypto_perp')
         */
        market?: string | null;
    };
    url: '/api/portfolio/performance';
};

export type GetPerformanceApiPortfolioPerformanceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPerformanceApiPortfolioPerformanceGetError = GetPerformanceApiPortfolioPerformanceGetErrors[keyof GetPerformanceApiPortfolioPerformanceGetErrors];

export type GetPerformanceApiPortfolioPerformanceGetResponses = {
    /**
     * Successful Response
     */
    200: PerformanceSummaryResponse;
};

export type GetPerformanceApiPortfolioPerformanceGetResponse = GetPerformanceApiPortfolioPerformanceGetResponses[keyof GetPerformanceApiPortfolioPerformanceGetResponses];

export type GetHoldingsApiPortfolioHoldingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/holdings';
};

export type GetHoldingsApiPortfolioHoldingsGetResponses = {
    /**
     * Successful Response
     */
    200: HoldingsResponse;
};

export type GetHoldingsApiPortfolioHoldingsGetResponse = GetHoldingsApiPortfolioHoldingsGetResponses[keyof GetHoldingsApiPortfolioHoldingsGetResponses];

export type GetOrdersApiPortfolioOrdersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         *
         * Filter by order status
         */
        status?: string | null;
        /**
         * Limit
         *
         * Max orders to return
         */
        limit?: number;
    };
    url: '/api/portfolio/orders';
};

export type GetOrdersApiPortfolioOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersApiPortfolioOrdersGetError = GetOrdersApiPortfolioOrdersGetErrors[keyof GetOrdersApiPortfolioOrdersGetErrors];

export type GetOrdersApiPortfolioOrdersGetResponses = {
    /**
     * Successful Response
     */
    200: OrdersResponse;
};

export type GetOrdersApiPortfolioOrdersGetResponse = GetOrdersApiPortfolioOrdersGetResponses[keyof GetOrdersApiPortfolioOrdersGetResponses];

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/perp-holdings';
};

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses = {
    /**
     * Successful Response
     */
    200: PerpHoldingsResponse;
};

export type GetPerpHoldingsApiPortfolioPerpHoldingsGetResponse = GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses[keyof GetPerpHoldingsApiPortfolioPerpHoldingsGetResponses];

export type GetNotificationsApiNotificationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Source
         *
         * Filter by source: risk, data_quality, autoresearch
         */
        source?: string | null;
    };
    url: '/api/notifications';
};

export type GetNotificationsApiNotificationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotificationsApiNotificationsGetError = GetNotificationsApiNotificationsGetErrors[keyof GetNotificationsApiNotificationsGetErrors];

export type GetNotificationsApiNotificationsGetResponses = {
    /**
     * Successful Response
     */
    200: NotificationsResponse;
};

export type GetNotificationsApiNotificationsGetResponse = GetNotificationsApiNotificationsGetResponses[keyof GetNotificationsApiNotificationsGetResponses];

// --- Phase 40: Data Coverage / Gaps / Freshness (manually added; regen on stormtrooper deployment) ---

/**
 * DataCoverageResponse
 *
 * Per-(market, symbol, interval) coverage from data_coverage_mv (Phase 39).
 */
export type DataCoverageResponse = {
    market: string;
    symbol: string;
    interval: string;
    first_ts: string | null;
    last_ts: string | null;
    row_count: number;
    expected_count: number;
    gap_count: number;
    completeness_pct: number;
    staleness_seconds: number;
    health: string;
};

/**
 * DataGapResponse
 *
 * Per-gap window from data_gaps table (Phase 40 D-02, D-04).
 */
export type DataGapResponse = {
    gap_id: string;
    market: string;
    symbol: string;
    interval: string;
    gap_start: string;
    gap_end: string;
    missing_bars: number;
    detected_at: string;
    healed_at: string | null;
};

/**
 * DataFreshnessResponse
 *
 * Per-(market, interval) freshness snapshot (Phase 40 D-03, D-11, D-16).
 */
export type DataFreshnessResponse = {
    market: string;
    interval: string;
    last_successful_ts: string | null;
    expected_lag_seconds: number;
    observed_lag_seconds: number;
    status: string;
};

export type GetDataCoverageApiDataCoverageGetData = {
    body?: never;
    path?: never;
    query?: {
        market?: string | null;
        symbol?: string | null;
        interval?: string | null;
    };
    url: '/api/data/coverage';
};

export type GetDataCoverageApiDataCoverageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDataCoverageApiDataCoverageGetError = GetDataCoverageApiDataCoverageGetErrors[keyof GetDataCoverageApiDataCoverageGetErrors];

export type GetDataCoverageApiDataCoverageGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DataCoverageResponse>;
};

export type GetDataCoverageApiDataCoverageGetResponse = GetDataCoverageApiDataCoverageGetResponses[keyof GetDataCoverageApiDataCoverageGetResponses];

export type GetDataGapsApiDataGapsGetData = {
    body?: never;
    path?: never;
    query?: {
        market?: string | null;
        symbol?: string | null;
        interval?: string | null;
        open_only?: boolean;
    };
    url: '/api/data/gaps';
};

export type GetDataGapsApiDataGapsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDataGapsApiDataGapsGetError = GetDataGapsApiDataGapsGetErrors[keyof GetDataGapsApiDataGapsGetErrors];

export type GetDataGapsApiDataGapsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DataGapResponse>;
};

export type GetDataGapsApiDataGapsGetResponse = GetDataGapsApiDataGapsGetResponses[keyof GetDataGapsApiDataGapsGetResponses];

export type GetDataFreshnessApiDataFreshnessGetData = {
    body?: never;
    path?: never;
    query?: {
        market?: string | null;
    };
    url: '/api/data/freshness';
};

export type GetDataFreshnessApiDataFreshnessGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDataFreshnessApiDataFreshnessGetError = GetDataFreshnessApiDataFreshnessGetErrors[keyof GetDataFreshnessApiDataFreshnessGetErrors];

export type GetDataFreshnessApiDataFreshnessGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DataFreshnessResponse>;
};

export type GetDataFreshnessApiDataFreshnessGetResponse = GetDataFreshnessApiDataFreshnessGetResponses[keyof GetDataFreshnessApiDataFreshnessGetResponses];
