// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_create_task_with_upload_tasks_upload_post
 */
export type BodyCreateTaskWithUploadTasksUploadPost = {
    /**
     * File
     */
    file: string;
};

/**
 * DeviceType
 */
export type DeviceType = 'gpu' | 'cpu' | 'auto';

/**
 * DocumentCreate
 */
export type DocumentCreate = {
    /**
     * Type
     */
    type: string;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DocumentListResponse
 */
export type DocumentListResponse = {
    /**
     * Documents
     */
    documents: Array<DocumentResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * DocumentResponse
 */
export type DocumentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Gpu Available
     */
    gpu_available: boolean;
    /**
     * Gpu Memory Used Mb
     */
    gpu_memory_used_mb: number | null;
    /**
     * Gpu Memory Total Mb
     */
    gpu_memory_total_mb: number | null;
    /**
     * Queue Gpu Length
     */
    queue_gpu_length: number;
    /**
     * Queue Cpu Length
     */
    queue_cpu_length: number;
};

/**
 * ScheduleCreate
 */
export type ScheduleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Cron Expression
     */
    cron_expression: string;
    type: TaskType;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
};

/**
 * ScheduleResponse
 */
export type ScheduleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Cron Expression
     */
    cron_expression: string;
    /**
     * Type
     */
    type: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Last Run
     */
    last_run: string | null;
    /**
     * Next Run
     */
    next_run: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ScheduleUpdate
 */
export type ScheduleUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Cron Expression
     */
    cron_expression?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    type: TaskType;
    /**
     * Source Url
     */
    source_url?: string | null;
    device?: DeviceType;
};

/**
 * TaskListResponse
 */
export type TaskListResponse = {
    /**
     * Tasks
     */
    tasks: Array<TaskResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * TaskResponse
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: string;
    type: TaskType;
    /**
     * Source Url
     */
    source_url: string | null;
    status: TaskStatus;
    /**
     * Step
     */
    step: string | null;
    /**
     * Result Text
     */
    result_text: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Device
     */
    device: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'queued' | 'downloading' | 'processing' | 'completed' | 'failed';

/**
 * TaskType
 */
export type TaskType = 'youtube' | 'podcast' | 'video' | 'audio' | 'pdf' | 'image';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListTasksTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: TaskType | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/tasks';
};

export type ListTasksTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksTasksGetError = ListTasksTasksGetErrors[keyof ListTasksTasksGetErrors];

export type ListTasksTasksGetResponses = {
    /**
     * Successful Response
     */
    200: TaskListResponse;
};

export type ListTasksTasksGetResponse = ListTasksTasksGetResponses[keyof ListTasksTasksGetResponses];

export type CreateTaskTasksPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type CreateTaskTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTasksPostError = CreateTaskTasksPostErrors[keyof CreateTaskTasksPostErrors];

export type CreateTaskTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskResponse;
};

export type CreateTaskTasksPostResponse = CreateTaskTasksPostResponses[keyof CreateTaskTasksPostResponses];

export type CreateTaskWithUploadTasksUploadPostData = {
    body: BodyCreateTaskWithUploadTasksUploadPost;
    path?: never;
    query: {
        type: TaskType;
        device?: DeviceType;
    };
    url: '/tasks/upload';
};

export type CreateTaskWithUploadTasksUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskWithUploadTasksUploadPostError = CreateTaskWithUploadTasksUploadPostErrors[keyof CreateTaskWithUploadTasksUploadPostErrors];

export type CreateTaskWithUploadTasksUploadPostResponses = {
    /**
     * Successful Response
     */
    201: TaskResponse;
};

export type CreateTaskWithUploadTasksUploadPostResponse = CreateTaskWithUploadTasksUploadPostResponses[keyof CreateTaskWithUploadTasksUploadPostResponses];

export type DeleteTaskTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskTasksTaskIdDeleteError = DeleteTaskTasksTaskIdDeleteErrors[keyof DeleteTaskTasksTaskIdDeleteErrors];

export type DeleteTaskTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskTasksTaskIdDeleteResponse = DeleteTaskTasksTaskIdDeleteResponses[keyof DeleteTaskTasksTaskIdDeleteResponses];

export type GetTaskTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTaskTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskTasksTaskIdGetError = GetTaskTasksTaskIdGetErrors[keyof GetTaskTasksTaskIdGetErrors];

export type GetTaskTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskTasksTaskIdGetResponse = GetTaskTasksTaskIdGetResponses[keyof GetTaskTasksTaskIdGetResponses];

export type ListDocumentsDocumentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/documents';
};

export type ListDocumentsDocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsDocumentsGetError = ListDocumentsDocumentsGetErrors[keyof ListDocumentsDocumentsGetErrors];

export type ListDocumentsDocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentListResponse;
};

export type ListDocumentsDocumentsGetResponse = ListDocumentsDocumentsGetResponses[keyof ListDocumentsDocumentsGetResponses];

export type CreateDocumentDocumentsPostData = {
    body: DocumentCreate;
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDocumentDocumentsPostError = CreateDocumentDocumentsPostErrors[keyof CreateDocumentDocumentsPostErrors];

export type CreateDocumentDocumentsPostResponses = {
    /**
     * Successful Response
     */
    201: DocumentResponse;
};

export type CreateDocumentDocumentsPostResponse = CreateDocumentDocumentsPostResponses[keyof CreateDocumentDocumentsPostResponses];

export type GetDocumentDocumentsDocumentIdGetData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}';
};

export type GetDocumentDocumentsDocumentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentDocumentsDocumentIdGetError = GetDocumentDocumentsDocumentIdGetErrors[keyof GetDocumentDocumentsDocumentIdGetErrors];

export type GetDocumentDocumentsDocumentIdGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponse;
};

export type GetDocumentDocumentsDocumentIdGetResponse = GetDocumentDocumentsDocumentIdGetResponses[keyof GetDocumentDocumentsDocumentIdGetResponses];

export type ListSchedulesSchedulesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schedules';
};

export type ListSchedulesSchedulesGetResponses = {
    /**
     * Response List Schedules Schedules Get
     *
     * Successful Response
     */
    200: Array<ScheduleResponse>;
};

export type ListSchedulesSchedulesGetResponse = ListSchedulesSchedulesGetResponses[keyof ListSchedulesSchedulesGetResponses];

export type CreateScheduleSchedulesPostData = {
    body: ScheduleCreate;
    path?: never;
    query?: never;
    url: '/schedules';
};

export type CreateScheduleSchedulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScheduleSchedulesPostError = CreateScheduleSchedulesPostErrors[keyof CreateScheduleSchedulesPostErrors];

export type CreateScheduleSchedulesPostResponses = {
    /**
     * Successful Response
     */
    201: ScheduleResponse;
};

export type CreateScheduleSchedulesPostResponse = CreateScheduleSchedulesPostResponses[keyof CreateScheduleSchedulesPostResponses];

export type DeleteScheduleSchedulesScheduleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: string;
    };
    query?: never;
    url: '/schedules/{schedule_id}';
};

export type DeleteScheduleSchedulesScheduleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScheduleSchedulesScheduleIdDeleteError = DeleteScheduleSchedulesScheduleIdDeleteErrors[keyof DeleteScheduleSchedulesScheduleIdDeleteErrors];

export type DeleteScheduleSchedulesScheduleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScheduleSchedulesScheduleIdDeleteResponse = DeleteScheduleSchedulesScheduleIdDeleteResponses[keyof DeleteScheduleSchedulesScheduleIdDeleteResponses];

export type UpdateScheduleSchedulesScheduleIdPutData = {
    body: ScheduleUpdate;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: string;
    };
    query?: never;
    url: '/schedules/{schedule_id}';
};

export type UpdateScheduleSchedulesScheduleIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScheduleSchedulesScheduleIdPutError = UpdateScheduleSchedulesScheduleIdPutErrors[keyof UpdateScheduleSchedulesScheduleIdPutErrors];

export type UpdateScheduleSchedulesScheduleIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScheduleResponse;
};

export type UpdateScheduleSchedulesScheduleIdPutResponse = UpdateScheduleSchedulesScheduleIdPutResponses[keyof UpdateScheduleSchedulesScheduleIdPutResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
