// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createDocumentDocumentsPost, createScheduleSchedulesPost, createTaskTasksPost, createTaskWithUploadTasksUploadPost, deleteScheduleSchedulesScheduleIdDelete, deleteTaskTasksTaskIdDelete, getDocumentDocumentsDocumentIdGet, getTaskTasksTaskIdGet, healthCheckHealthGet, listDocumentsDocumentsGet, listSchedulesSchedulesGet, listTasksTasksGet, type Options, updateScheduleSchedulesScheduleIdPut } from '../sdk.gen';
import type { CreateDocumentDocumentsPostData, CreateDocumentDocumentsPostError, CreateDocumentDocumentsPostResponse, CreateScheduleSchedulesPostData, CreateScheduleSchedulesPostError, CreateScheduleSchedulesPostResponse, CreateTaskTasksPostData, CreateTaskTasksPostError, CreateTaskTasksPostResponse, CreateTaskWithUploadTasksUploadPostData, CreateTaskWithUploadTasksUploadPostError, CreateTaskWithUploadTasksUploadPostResponse, DeleteScheduleSchedulesScheduleIdDeleteData, DeleteScheduleSchedulesScheduleIdDeleteError, DeleteScheduleSchedulesScheduleIdDeleteResponse, DeleteTaskTasksTaskIdDeleteData, DeleteTaskTasksTaskIdDeleteError, DeleteTaskTasksTaskIdDeleteResponse, GetDocumentDocumentsDocumentIdGetData, GetDocumentDocumentsDocumentIdGetError, GetDocumentDocumentsDocumentIdGetResponse, GetTaskTasksTaskIdGetData, GetTaskTasksTaskIdGetError, GetTaskTasksTaskIdGetResponse, HealthCheckHealthGetData, HealthCheckHealthGetResponse, ListDocumentsDocumentsGetData, ListDocumentsDocumentsGetError, ListDocumentsDocumentsGetResponse, ListSchedulesSchedulesGetData, ListSchedulesSchedulesGetResponse, ListTasksTasksGetData, ListTasksTasksGetError, ListTasksTasksGetResponse, UpdateScheduleSchedulesScheduleIdPutData, UpdateScheduleSchedulesScheduleIdPutError, UpdateScheduleSchedulesScheduleIdPutResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const listTasksTasksGetQueryKey = (options?: Options<ListTasksTasksGetData>) => createQueryKey("listTasksTasksGet", options);

/**
 * List Tasks
 */
export const listTasksTasksGetOptions = (options?: Options<ListTasksTasksGetData>) => queryOptions<ListTasksTasksGetResponse, ListTasksTasksGetError, ListTasksTasksGetResponse, ReturnType<typeof listTasksTasksGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTasksTasksGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTasksTasksGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listTasksTasksGetInfiniteQueryKey = (options?: Options<ListTasksTasksGetData>): QueryKey<Options<ListTasksTasksGetData>> => createQueryKey("listTasksTasksGet", options, true);

/**
 * List Tasks
 */
export const listTasksTasksGetInfiniteOptions = (options?: Options<ListTasksTasksGetData>) => {
    return infiniteQueryOptions<ListTasksTasksGetResponse, ListTasksTasksGetError, InfiniteData<ListTasksTasksGetResponse>, QueryKey<Options<ListTasksTasksGetData>>, number | Pick<QueryKey<Options<ListTasksTasksGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListTasksTasksGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listTasksTasksGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listTasksTasksGetInfiniteQueryKey(options)
    });
};

/**
 * Create Task
 */
export const createTaskTasksPostMutation = (options?: Partial<Options<CreateTaskTasksPostData>>): UseMutationOptions<CreateTaskTasksPostResponse, CreateTaskTasksPostError, Options<CreateTaskTasksPostData>> => {
    const mutationOptions: UseMutationOptions<CreateTaskTasksPostResponse, CreateTaskTasksPostError, Options<CreateTaskTasksPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTaskTasksPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Task With Upload
 */
export const createTaskWithUploadTasksUploadPostMutation = (options?: Partial<Options<CreateTaskWithUploadTasksUploadPostData>>): UseMutationOptions<CreateTaskWithUploadTasksUploadPostResponse, CreateTaskWithUploadTasksUploadPostError, Options<CreateTaskWithUploadTasksUploadPostData>> => {
    const mutationOptions: UseMutationOptions<CreateTaskWithUploadTasksUploadPostResponse, CreateTaskWithUploadTasksUploadPostError, Options<CreateTaskWithUploadTasksUploadPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTaskWithUploadTasksUploadPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Task
 */
export const deleteTaskTasksTaskIdDeleteMutation = (options?: Partial<Options<DeleteTaskTasksTaskIdDeleteData>>): UseMutationOptions<DeleteTaskTasksTaskIdDeleteResponse, DeleteTaskTasksTaskIdDeleteError, Options<DeleteTaskTasksTaskIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteTaskTasksTaskIdDeleteResponse, DeleteTaskTasksTaskIdDeleteError, Options<DeleteTaskTasksTaskIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTaskTasksTaskIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTaskTasksTaskIdGetQueryKey = (options: Options<GetTaskTasksTaskIdGetData>) => createQueryKey("getTaskTasksTaskIdGet", options);

/**
 * Get Task
 */
export const getTaskTasksTaskIdGetOptions = (options: Options<GetTaskTasksTaskIdGetData>) => queryOptions<GetTaskTasksTaskIdGetResponse, GetTaskTasksTaskIdGetError, GetTaskTasksTaskIdGetResponse, ReturnType<typeof getTaskTasksTaskIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTaskTasksTaskIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTaskTasksTaskIdGetQueryKey(options)
});

export const listDocumentsDocumentsGetQueryKey = (options?: Options<ListDocumentsDocumentsGetData>) => createQueryKey("listDocumentsDocumentsGet", options);

/**
 * List Documents
 */
export const listDocumentsDocumentsGetOptions = (options?: Options<ListDocumentsDocumentsGetData>) => queryOptions<ListDocumentsDocumentsGetResponse, ListDocumentsDocumentsGetError, ListDocumentsDocumentsGetResponse, ReturnType<typeof listDocumentsDocumentsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDocumentsDocumentsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDocumentsDocumentsGetQueryKey(options)
});

export const listDocumentsDocumentsGetInfiniteQueryKey = (options?: Options<ListDocumentsDocumentsGetData>): QueryKey<Options<ListDocumentsDocumentsGetData>> => createQueryKey("listDocumentsDocumentsGet", options, true);

/**
 * List Documents
 */
export const listDocumentsDocumentsGetInfiniteOptions = (options?: Options<ListDocumentsDocumentsGetData>) => {
    return infiniteQueryOptions<ListDocumentsDocumentsGetResponse, ListDocumentsDocumentsGetError, InfiniteData<ListDocumentsDocumentsGetResponse>, QueryKey<Options<ListDocumentsDocumentsGetData>>, number | Pick<QueryKey<Options<ListDocumentsDocumentsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListDocumentsDocumentsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listDocumentsDocumentsGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listDocumentsDocumentsGetInfiniteQueryKey(options)
    });
};

/**
 * Create Document
 */
export const createDocumentDocumentsPostMutation = (options?: Partial<Options<CreateDocumentDocumentsPostData>>): UseMutationOptions<CreateDocumentDocumentsPostResponse, CreateDocumentDocumentsPostError, Options<CreateDocumentDocumentsPostData>> => {
    const mutationOptions: UseMutationOptions<CreateDocumentDocumentsPostResponse, CreateDocumentDocumentsPostError, Options<CreateDocumentDocumentsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createDocumentDocumentsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDocumentDocumentsDocumentIdGetQueryKey = (options: Options<GetDocumentDocumentsDocumentIdGetData>) => createQueryKey("getDocumentDocumentsDocumentIdGet", options);

/**
 * Get Document
 */
export const getDocumentDocumentsDocumentIdGetOptions = (options: Options<GetDocumentDocumentsDocumentIdGetData>) => queryOptions<GetDocumentDocumentsDocumentIdGetResponse, GetDocumentDocumentsDocumentIdGetError, GetDocumentDocumentsDocumentIdGetResponse, ReturnType<typeof getDocumentDocumentsDocumentIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDocumentDocumentsDocumentIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDocumentDocumentsDocumentIdGetQueryKey(options)
});

export const listSchedulesSchedulesGetQueryKey = (options?: Options<ListSchedulesSchedulesGetData>) => createQueryKey("listSchedulesSchedulesGet", options);

/**
 * List Schedules
 */
export const listSchedulesSchedulesGetOptions = (options?: Options<ListSchedulesSchedulesGetData>) => queryOptions<ListSchedulesSchedulesGetResponse, DefaultError, ListSchedulesSchedulesGetResponse, ReturnType<typeof listSchedulesSchedulesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSchedulesSchedulesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSchedulesSchedulesGetQueryKey(options)
});

/**
 * Create Schedule
 */
export const createScheduleSchedulesPostMutation = (options?: Partial<Options<CreateScheduleSchedulesPostData>>): UseMutationOptions<CreateScheduleSchedulesPostResponse, CreateScheduleSchedulesPostError, Options<CreateScheduleSchedulesPostData>> => {
    const mutationOptions: UseMutationOptions<CreateScheduleSchedulesPostResponse, CreateScheduleSchedulesPostError, Options<CreateScheduleSchedulesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createScheduleSchedulesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Schedule
 */
export const deleteScheduleSchedulesScheduleIdDeleteMutation = (options?: Partial<Options<DeleteScheduleSchedulesScheduleIdDeleteData>>): UseMutationOptions<DeleteScheduleSchedulesScheduleIdDeleteResponse, DeleteScheduleSchedulesScheduleIdDeleteError, Options<DeleteScheduleSchedulesScheduleIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteScheduleSchedulesScheduleIdDeleteResponse, DeleteScheduleSchedulesScheduleIdDeleteError, Options<DeleteScheduleSchedulesScheduleIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteScheduleSchedulesScheduleIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Schedule
 */
export const updateScheduleSchedulesScheduleIdPutMutation = (options?: Partial<Options<UpdateScheduleSchedulesScheduleIdPutData>>): UseMutationOptions<UpdateScheduleSchedulesScheduleIdPutResponse, UpdateScheduleSchedulesScheduleIdPutError, Options<UpdateScheduleSchedulesScheduleIdPutData>> => {
    const mutationOptions: UseMutationOptions<UpdateScheduleSchedulesScheduleIdPutResponse, UpdateScheduleSchedulesScheduleIdPutError, Options<UpdateScheduleSchedulesScheduleIdPutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateScheduleSchedulesScheduleIdPut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey("healthCheckHealthGet", options);

/**
 * Health Check
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => queryOptions<HealthCheckHealthGetResponse, DefaultError, HealthCheckHealthGetResponse, ReturnType<typeof healthCheckHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options)
});
